// Single source of truth for Tauranto's governed executable intents.
export const ACTION_INTENTS = [
  "menu_availability","business_hours","pause_orders","supplier_email","purchase_request","contact_message","calendar_reminder","schedule_meeting","update_meeting","cancel_meeting","send_email","crm_contact_create","crm_contact_update","crm_note","crm_task","square_catalog_update","square_order","toast_menu_update","toast_order_action","zoom_meeting","customer_followup","announcement","internal_task","website_update",
  "delivery_order_lookup","delivery_order_update","delivery_pause_store","delivery_resume_store","delivery_message","customer_message","staff_message","staff_schedule_lookup","staff_schedule_update","staff_shift_cancel","staff_shift_publish","reservation_lookup","reservation_create","reservation_update","reservation_cancel","inventory_lookup","inventory_adjust","supplier_order","accounting_lookup","report_export"
] as const;
export type ActionIntent=(typeof ACTION_INTENTS)[number];
export const ACTION_LABELS:Record<ActionIntent,string>={
menu_availability:"Menu item availability",business_hours:"Business hours changes",pause_orders:"Pause online ordering",supplier_email:"Supplier emails",purchase_request:"Purchase / supply orders",contact_message:"Message a directory contact",calendar_reminder:"Reminders & tasks",schedule_meeting:"Schedule a meeting",update_meeting:"Update a meeting",cancel_meeting:"Cancel a meeting",send_email:"Send email",crm_contact_create:"Create CRM contact",crm_contact_update:"Update CRM contact",crm_note:"Add CRM note",crm_task:"Create CRM task",square_catalog_update:"Update Square catalog",square_order:"Square order actions",toast_menu_update:"Update Toast menu",toast_order_action:"Toast order actions",zoom_meeting:"Create Zoom meeting",customer_followup:"Customer follow-up",announcement:"Team announcement",internal_task:"Internal task",website_update:"Website update",
delivery_order_lookup:"Look up delivery orders",delivery_order_update:"Update delivery order",delivery_pause_store:"Pause delivery storefront",delivery_resume_store:"Resume delivery storefront",delivery_message:"Delivery communication",customer_message:"Customer communication",staff_message:"Staff communication",staff_schedule_lookup:"View staff schedule",staff_schedule_update:"Update staff schedule",staff_shift_cancel:"Cancel staff shift",staff_shift_publish:"Publish staff schedule",reservation_lookup:"Look up reservations",reservation_create:"Create reservation",reservation_update:"Update reservation",reservation_cancel:"Cancel reservation",inventory_lookup:"Check inventory",inventory_adjust:"Adjust inventory",supplier_order:"Place supplier order",accounting_lookup:"Accounting lookup",report_export:"Export report"};
export const MEMBER_ROLES=["owner","admin","manager","operator","server","viewer"] as const;export type MemberRole=(typeof MEMBER_ROLES)[number];
export const ROLE_LABELS:Record<MemberRole,string>={owner:"Owner",admin:"Admin",manager:"Manager",operator:"Operator",server:"Server",viewer:"Viewer"};
export const RISK_LEVELS=["low","medium","high","critical"] as const;export type RiskLevel=(typeof RISK_LEVELS)[number];export const RISK_RANK:Record<RiskLevel,number>={low:0,medium:1,high:2,critical:3};
export const DEFAULT_ROLE_MAX_RISK:Record<MemberRole,RiskLevel>={owner:"critical",admin:"critical",manager:"high",operator:"medium",server:"low",viewer:"low"};