import React, { useState } from "react";
import { ScrollView, View, Text, Pressable, StyleSheet } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import { VoiceCommand } from "../lib/models";
import { colors, radius } from "../theme/tokens";

export function ActivityScreen({ commands, onDecide }: { commands: VoiceCommand[]; onDecide: (id: string, approved: boolean) => void }) {
  const insets=useSafeAreaInsets(); const [filter,setFilter]=useState<"All"|"Pending"|"Completed">("All");
  const fallback:VoiceCommand[]=[{id:"demo-1",transcript:"Post today's lamb special to the website",title:"Published lunch special",summary:"Lamb kofta bowl · $19 · available until 4 PM",type:"announcement",status:"approved",createdAt:new Date(Date.now()-27*60000).toISOString(),targets:["Website"],confidence:.96},{id:"demo-2",transcript:"Remind me to check the freezer tomorrow",title:"Freezer inspection reminder",summary:"Scheduled for tomorrow at 8:30 AM",type:"reminder",status:"completed",createdAt:new Date(Date.now()-70*60000).toISOString(),targets:["Calendar"],confidence:.95}];
  const all=[...commands,...fallback]; const visible=all.filter((item)=>filter==="All"||(filter==="Pending"&&item.status==="pending")||(filter==="Completed"&&item.status!=="pending"));
  return <ScrollView style={styles.page} contentContainerStyle={{paddingTop:insets.top+13,paddingHorizontal:17,paddingBottom:30}}><Text style={styles.kicker}>COMMAND HISTORY</Text><Text style={styles.title}>Activity & approvals</Text><Text style={styles.subtitle}>Every instruction, decision and connected-system response in one place.</Text>
    <View style={styles.filters}>{(["All","Pending","Completed"] as const).map((name)=><Pressable key={name} onPress={()=>setFilter(name)} style={[styles.filter,filter===name&&styles.filterActive]}><Text style={[styles.filterText,filter===name&&styles.filterTextActive]}>{name}</Text></Pressable>)}</View>
    {visible.length===0?<View style={styles.blank}><Ionicons name="file-tray-outline" size={30} color={colors.leaf}/><Text style={styles.blankTitle}>Nothing here yet</Text><Text style={styles.blankCopy}>Commands matching this filter will appear here.</Text></View>:visible.map((item)=><View key={item.id} style={styles.item}><View style={[styles.icon,{backgroundColor:item.status==="pending"?colors.tomatoPale:colors.leafPale}]}><Ionicons name={item.status==="pending"?"hourglass-outline":"checkmark"} size={17} color={item.status==="pending"?colors.tomato:colors.leafDeep}/></View><View style={{flex:1}}><View style={styles.itemTop}><Text style={styles.itemTitle}>{item.title}</Text><Text style={[styles.state,item.status==="pending"&&styles.statePending]}>{item.status}</Text></View><Text style={styles.summary}>{item.summary}</Text><Text style={styles.quote}>“{item.transcript}”</Text><View style={styles.meta}><Text>{new Date(item.createdAt).toLocaleTimeString([], {hour:"numeric",minute:"2-digit"})}</Text><Text>•</Text><Text>{item.targets.join(" + ")}</Text></View>{item.status==="pending"&&<View style={styles.actions}><Pressable onPress={()=>onDecide(item.id,false)} style={styles.secondary}><Text>Dismiss</Text></Pressable><Pressable onPress={()=>onDecide(item.id,true)} style={styles.primary}><Text>Approve</Text></Pressable></View>}</View></View>)}
  </ScrollView>;
}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:colors.cream},kicker:{fontFamily:"DMSans_700Bold",fontSize:8,letterSpacing:1.2,color:colors.leafDeep},title:{fontFamily:"DMSans_700Bold",fontSize:27,color:colors.ink,marginTop:5},subtitle:{fontFamily:"DMSans_400Regular",fontSize:11,lineHeight:17,color:colors.muted,marginTop:6,maxWidth:340},filters:{flexDirection:"row",gap:7,marginVertical:18},filter:{paddingHorizontal:14,paddingVertical:8,borderRadius:20,borderWidth:1,borderColor:colors.line,backgroundColor:colors.paper},filterActive:{backgroundColor:colors.leafDeep,borderColor:colors.leafDeep},filterText:{fontFamily:"DMSans_700Bold",fontSize:9,color:colors.inkSoft},filterTextActive:{color:"white"},item:{flexDirection:"row",gap:11,backgroundColor:colors.paper,borderRadius:radius.lg,borderWidth:1,borderColor:colors.line,padding:14,marginBottom:10},icon:{width:36,height:36,borderRadius:12,alignItems:"center",justifyContent:"center"},itemTop:{flexDirection:"row",gap:6,alignItems:"flex-start"},itemTitle:{flex:1,fontFamily:"DMSans_700Bold",fontSize:12,color:colors.ink},state:{fontFamily:"DMSans_700Bold",fontSize:7,textTransform:"uppercase",color:colors.leafDeep,backgroundColor:colors.leafPale,paddingHorizontal:7,paddingVertical:4,borderRadius:6},statePending:{color:colors.tomato,backgroundColor:colors.tomatoPale},summary:{fontFamily:"DMSans_400Regular",fontSize:10,lineHeight:15,color:colors.inkSoft,marginTop:5},quote:{fontFamily:"DMSans_500Medium",fontSize:9,color:colors.muted,marginTop:9},meta:{flexDirection:"row",gap:5,marginTop:8},actions:{flexDirection:"row",gap:7,marginTop:11},secondary:{flex:1,borderWidth:1,borderColor:colors.line,borderRadius:10,padding:9,alignItems:"center"},primary:{flex:1,backgroundColor:colors.leafDeep,borderRadius:10,padding:9,alignItems:"center"},blank:{alignItems:"center",backgroundColor:colors.paper,borderRadius:radius.lg,padding:35,borderWidth:1,borderColor:colors.line},blankTitle:{fontFamily:"DMSans_700Bold",fontSize:13,color:colors.ink,marginTop:9},blankCopy:{fontFamily:"DMSans_400Regular",fontSize:10,color:colors.muted,marginTop:4}});
