import React, { useState } from "react";
import { ScrollView, View, Text, Pressable, StyleSheet } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import { VoiceCommand } from "../lib/models";
import { colors, radius } from "../theme/tokens";

export function ActivityScreen({ commands, onDecide }: { commands: VoiceCommand[]; onDecide: (id: string, approved: boolean) => void }) {
  const insets=useSafeAreaInsets(); const [filter,setFilter]=useState<"All"|"Pending"|"Completed">("All");
  const fallback:VoiceCommand[]=[{id:"demo-1",transcript:"Post today's lamb special to the website",title:"Published lunch special",summary:"Lamb kofta bowl · $19 · available until 4 PM",type:"announcement",status:"approved",createdAt:new Date(Date.now()-27*60000).toISOString(),targets:["Website"],confidence:.96},{id:"demo-2",transcript:"Remind me to check the freezer tomorrow",title:"Freezer inspection reminder",summary:"Scheduled for tomorrow at 8:30 AM",type:"reminder",status:"completed",createdAt:new Date(Date.now()-70*60000).toISOString(),targets:["Calendar"],confidence:.95}];
  const all=[...commands,...fallback]; const visible=all.filter((item)=>filter==="All"||(filter==="Pending"&&item.status==="pending")||(filter==="Completed"&&item.status!=="pending"));
  return <ScrollView style={styles.page} contentContainerStyle={{paddingTop:insets.top+13,paddingHorizontal:17,paddingBottom:30}}><Text style={styles.kicker}>COMMAND HISTORY</Text><Text style={styles.title}>Activity & approvals</Text><Text style={styles.subtitle}>Every instruction, decision and connected-system response in one place.</Text>
    <View style={styles.filters}>{(["All","Pending","Completed"] as const).map((name)=><Pressable key={name} onPress={()=>setFilter(name)} style={[styles.filter,filter===name&&styles.filterActive]}><Text style={[styles.filterText,filter===name&&styles.filterTextActive]}>{name}</Text></Pressable>)}</View>
    {visible.length===0?<View style={styles.blank}><Ionicons name="file-tray-outline" size={30} color={colors.leaf}/><Text style={styles.blankTitle}>Nothing here yet</Text><Text style={styles.blankCopy}>Commands matching this filter will appear here.</Text></View>:visible.map((item)=><View key={item.id} style={styles.item}><View style={[styles.icon,{backgroundColor:item.status==="pending"?colors.tomatoPale:colors.leafPale}]}><Ionicons name={item.status==="pending"?"hourglass-outline":"checkmark"} size={17} color={item.status==="pending"?colors.tomato:colors.leafDeep}/></View><View style={{flex:1}}><View style={styles.itemTop}><Text style={styles.itemTitle}>{item.title}</Text><Text style={[styles.state,item.status==="pending"&&styles.statePending]}>{item.status}</Text></View><Text style={styles.summary}>{item.summary}</Text><Text style={styles.quote}>“{item.transcript}”</Text><View style={styles.meta}><Text>{new Date(item.createdAt).toLocaleTimeString([], {hour:"numeric",minute:"2-digit"})}</Text><Text>•</Text><Text>{item.targets.join(" + ")}</Text></View>{item.status==="pending"&&<View style={styles.actions}><Pressable onPress={()=>onDecide(item.id,false)} style={styles.secondary}><Text>Dismiss</Text></Pressable><Pressable onPress={()=>onDecide(item.id,true)} style={styles.primary}><Text>Approve</Text></Pressable></View>}</View></View>)}
  </ScrollView>;
}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:colors.cream},kicker:{fontFamily:"DMSans_700Bold",fontSize:10.5,letterSpacing:1.05,color:colors.leafDeep},title:{fontFamily:"DMSans_700Bold",fontSize:30,lineHeight:35,color:colors.ink,marginTop:6},subtitle:{fontFamily:"DMSans_400Regular",fontSize:13.5,lineHeight:20,color:colors.muted,marginTop:7,maxWidth:360},filters:{flexDirection:"row",gap:8,marginVertical:17},filter:{minHeight:42,paddingHorizontal:17,paddingVertical:10,borderRadius:22,borderWidth:1,borderColor:colors.line,backgroundColor:colors.paper,justifyContent:"center"},filterActive:{backgroundColor:colors.leafDeep,borderColor:colors.leafDeep},filterText:{fontFamily:"DMSans_700Bold",fontSize:11.5,color:colors.inkSoft},filterTextActive:{color:"white"},item:{flexDirection:"row",gap:12,backgroundColor:colors.paper,borderRadius:radius.lg,borderWidth:1,borderColor:colors.line,padding:16,marginBottom:11},icon:{width:42,height:42,borderRadius:13,alignItems:"center",justifyContent:"center"},itemTop:{flexDirection:"row",gap:7,alignItems:"flex-start"},itemTitle:{flex:1,fontFamily:"DMSans_700Bold",fontSize:15,color:colors.ink},state:{fontFamily:"DMSans_700Bold",fontSize:9,textTransform:"uppercase",color:colors.leafDeep,backgroundColor:colors.leafPale,paddingHorizontal:8,paddingVertical:5,borderRadius:7},statePending:{color:colors.tomato,backgroundColor:colors.tomatoPale},summary:{fontFamily:"DMSans_400Regular",fontSize:13,lineHeight:19,color:colors.inkSoft,marginTop:6},quote:{fontFamily:"DMSans_500Medium",fontSize:12,lineHeight:17,color:colors.muted,marginTop:10},meta:{flexDirection:"row",gap:6,marginTop:9},actions:{flexDirection:"row",gap:8,marginTop:13},secondary:{flex:1,minHeight:46,borderWidth:1,borderColor:colors.line,borderRadius:12,padding:11,alignItems:"center",justifyContent:"center"},primary:{flex:1,minHeight:46,backgroundColor:colors.leafDeep,borderRadius:12,padding:11,alignItems:"center",justifyContent:"center"},blank:{alignItems:"center",backgroundColor:colors.paper,borderRadius:radius.lg,padding:36,borderWidth:1,borderColor:colors.line},blankTitle:{fontFamily:"DMSans_700Bold",fontSize:16,color:colors.ink,marginTop:10},blankCopy:{fontFamily:"DMSans_400Regular",fontSize:12.5,lineHeight:18,color:colors.muted,marginTop:5}});
