import React,{useEffect,useState}from"react";
import{ActivityIndicator,AppState,Linking,Pressable,ScrollView,StyleSheet,Text,View}from"react-native";
import{appAlert}from"../components/AppAlert";
import{Ionicons}from"@expo/vector-icons";
import{useSafeAreaInsets}from"react-native-safe-area-context";
import{taurantoApi}from"../lib/api";
import{colors,darkColors,status,type}from"../theme/tokens";
import{useTheme}from"../theme/ThemeContext";
import{Skeleton,SkeletonCard}from"../components/Skeleton";
function billingTone(st?:string){if(st==="past_due"||st==="unpaid")return status.high;if(st==="trialing"||st==="incomplete")return status.medium;if(st==="canceled")return status.neutral;return status.low}

export function BillingScreen({restaurantId,onBack}:{restaurantId:string;onBack:()=>void}){
 const inset=useSafeAreaInsets(),[subscription,setSubscription]=useState<any>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState("");
 const{dark}=useTheme();
 const load=async()=>{setLoading(true);try{const x=await taurantoApi.subscription(restaurantId);setSubscription(x.subscription)}catch(e){appAlert("Billing unavailable",e instanceof Error?e.message:"Please retry.")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[restaurantId]);
 // Paid checkout finishes in the system browser, outside the app, so
 // refresh the plan as soon as the user comes back to it instead of leaving
 // a stale "current plan" showing until they manually reload.
 useEffect(()=>{const sub=AppState.addEventListener("change",v=>{if(v==="active")void load()});return()=>sub.remove()},[restaurantId]);
 const choose=async(id:"free"|"basic"|"enterprise")=>{if(subscription?.plans?.id===id)return;setBusy(id);try{if(id==="free"){const x=await taurantoApi.switchPlan(restaurantId,"free");setSubscription(x.subscription);appAlert("Plan updated",`Your restaurant is now on ${x.subscription.plans.name}.`)}else{const x=await taurantoApi.startCheckout(restaurantId,id);if(!x.checkoutUrl)throw new Error("Checkout could not be started.");await Linking.openURL(x.checkoutUrl)}}catch(e){appAlert(id==="free"?"Could not update plan":"Could not start checkout",e instanceof Error?e.message:"Please retry.")}finally{setBusy("")}};
 if(loading)return <ScrollView style={[s.page,dark&&s.pageDark]} contentContainerStyle={{paddingTop:inset.top+14,paddingHorizontal:18,paddingBottom:110}}><Skeleton width={130} height={13} style={{marginBottom:10}}/><Skeleton width={210} height={30} style={{marginBottom:20}}/><SkeletonCard lines={1} style={{marginBottom:14}}/><SkeletonCard lines={3}/><SkeletonCard lines={3}/><SkeletonCard lines={3}/></ScrollView>;
 return <ScrollView style={[s.page,dark&&s.pageDark]} contentContainerStyle={{paddingTop:inset.top+14,paddingHorizontal:18,paddingBottom:110}}><View style={s.header}><Pressable onPress={onBack} style={[s.back,dark&&s.backDark]}><Ionicons name="arrow-back" size={20} color={dark?darkColors.text:"#000"}/></Pressable><View><Text style={s.kicker}>ACCOUNT</Text><Text style={[s.title,dark&&s.titleDark]}>Plans & billing</Text></View></View><View style={[s.status,dark&&s.statusDark]}><View style={s.statusTop}><Text style={[s.statusLabel,dark&&s.statusLabelDark]}>CURRENT PLAN</Text><View style={[s.statusPill,{backgroundColor:billingTone(subscription?.status).bg}]}><Text style={[s.statusPillText,{color:billingTone(subscription?.status).fg}]}>{(subscription?.status||"active").replace("_"," ").toUpperCase()}</Text></View></View><Text style={[s.statusName,dark&&s.statusNameDark]}>{subscription?.plans?.name||"Free"}</Text><Text style={[s.statusCopy,dark&&s.statusCopyDark]}>Changes are saved to your restaurant subscription.</Text></View><Plan id="free" name="Free" price="$0" current={subscription?.plans?.id==="free"} busy={busy==="free"} onPress={()=>choose("free")} features={["Voice and typed commands","Recent activity","1 restaurant workspace","1 owner account"]}/><Plan id="basic" name="Basic" price="$30" current={subscription?.plans?.id==="basic"} busy={busy==="basic"} onPress={()=>choose("basic")} features={["Everything in Free","Manager approvals","Full activity history","Gmail, Calendar and website","Up to 3 managers"]}/><Plan id="enterprise" name="Enterprise" price="$65" current={subscription?.plans?.id==="enterprise"} busy={busy==="enterprise"} onPress={()=>choose("enterprise")} features={["Everything in Basic","POS and business integrations","Operations directory","Multi-location operations","Advanced audit controls"]}/></ScrollView>
}
function Plan({name,price,current,busy,onPress,features}:any){const{dark}=useTheme();return <View style={[s.plan,current&&s.currentPlan,dark&&s.planDark,current&&dark&&s.currentPlanDark]}><View style={s.planTop}><View><Text style={[s.planName,dark&&s.planNameDark]}>{name}</Text><Text><Text style={[s.price,dark&&s.priceDark]}>{price}</Text><Text style={[s.month,dark&&s.monthDark]}> / month</Text></Text></View>{current?<Text style={[s.current,dark&&s.currentDark]}>CURRENT</Text>:null}</View>{features.map((x:string)=><View key={x} style={s.feature}><Ionicons name="checkmark-circle" size={18} color={dark?colors.leaf:colors.leafInk}/><Text style={[s.featureText,dark&&s.featureTextDark]}>{x}</Text></View>)}<Pressable disabled={current||busy} onPress={onPress} style={[s.button,(current||busy)&&s.disabled]}>{busy?<ActivityIndicator color="#fff"/>:<Text style={s.buttonText}>{current?"Current plan":`Choose ${name}`}</Text>}</Pressable></View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:"#fff"},pageDark:{backgroundColor:darkColors.bg},loading:{flex:1,alignItems:"center",justifyContent:"center",backgroundColor:"#fff"},loadingDark:{backgroundColor:darkColors.bg},header:{flexDirection:"row",alignItems:"center",gap:11,marginBottom:17},back:{width:40,height:40,borderRadius:20,borderWidth:1,borderColor:"#DDE4E0",alignItems:"center",justifyContent:"center"},backDark:{backgroundColor:darkColors.circle,borderColor:darkColors.circleBorder},kicker:{...type.eyebrow,color:colors.leafInk},title:{...type.title,color:"#111613"},titleDark:{color:darkColors.text},status:{borderRadius:18,backgroundColor:"#ECFFF5",borderWidth:1,borderColor:colors.leafTint,padding:16,marginBottom:14},statusDark:{backgroundColor:darkColors.cardAlt,borderColor:darkColors.border},statusTop:{flexDirection:"row",alignItems:"center",justifyContent:"space-between"},statusLabel:{fontFamily:"NunitoSans_900Black",fontSize:9,letterSpacing:1.4,color:colors.leafInk},statusLabelDark:{color:darkColors.textMuted},statusPill:{paddingHorizontal:9,paddingVertical:5,borderRadius:999},statusPillText:{fontFamily:"NunitoSans_900Black",fontSize:8.5,letterSpacing:.3},statusName:{fontFamily:"NunitoSans_900Black",fontSize:22,color:"#111613",marginTop:5},statusNameDark:{color:darkColors.text},statusCopy:{fontFamily:"NunitoSans_600SemiBold",fontSize:12.5,lineHeight:18,color:"#69716C",marginTop:4,textTransform:"capitalize"},statusCopyDark:{color:darkColors.textMuted},plan:{borderWidth:1,borderColor:"#DDE4E0",borderRadius:19,padding:17,marginBottom:13},planDark:{backgroundColor:darkColors.card,borderColor:darkColors.border},currentPlan:{borderColor:"#7DDDB5",backgroundColor:"#FCFFFD"},currentPlanDark:{borderColor:colors.leaf,backgroundColor:darkColors.cardAlt},planTop:{flexDirection:"row",justifyContent:"space-between",marginBottom:14},planName:{fontFamily:"NunitoSans_900Black",fontSize:19,color:"#151A17"},planNameDark:{color:darkColors.text},price:{fontFamily:"NunitoSans_900Black",fontSize:27,color:colors.leafInk},priceDark:{color:colors.leaf},month:{fontFamily:"NunitoSans_600SemiBold",fontSize:12,color:"#737B76"},monthDark:{color:darkColors.textMuted},current:{fontFamily:"NunitoSans_900Black",fontSize:8.5,color:colors.leafInk,backgroundColor:"#E7F8EF",paddingHorizontal:9,paddingVertical:6,borderRadius:999},currentDark:{color:darkColors.bg,backgroundColor:colors.leaf},feature:{flexDirection:"row",alignItems:"center",gap:8,marginBottom:9},featureText:{fontFamily:"NunitoSans_700Bold",fontSize:12.5,color:"#434B46"},featureTextDark:{color:darkColors.textSoft},button:{height:48,borderRadius:13,backgroundColor:colors.leaf,alignItems:"center",justifyContent:"center",marginTop:7},buttonText:{fontFamily:"NunitoSans_900Black",fontSize:14,color:"#fff"},disabled:{opacity:.48}});
