import React,{useEffect,useState}from"react";
import{ActivityIndicator,Alert,AppState,Linking,Pressable,ScrollView,StyleSheet,Text,View}from"react-native";
import{Ionicons}from"@expo/vector-icons";
import{useSafeAreaInsets}from"react-native-safe-area-context";
import{taurantoApi}from"../lib/api";

export function BillingScreen({restaurantId,onBack}:{restaurantId:string;onBack:()=>void}){
 const inset=useSafeAreaInsets(),[subscription,setSubscription]=useState<any>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState("");
 const load=async()=>{setLoading(true);try{const x=await taurantoApi.subscription(restaurantId);setSubscription(x.subscription)}catch(e){Alert.alert("Billing unavailable",e instanceof Error?e.message:"Please retry.")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[restaurantId]);
 // Paid checkout finishes in the system browser, outside the app, so
 // refresh the plan as soon as the user comes back to it instead of leaving
 // a stale "current plan" showing until they manually reload.
 useEffect(()=>{const sub=AppState.addEventListener("change",v=>{if(v==="active")void load()});return()=>sub.remove()},[restaurantId]);
 const choose=async(id:"free"|"basic"|"enterprise")=>{if(subscription?.plans?.id===id)return;setBusy(id);try{if(id==="free"){const x=await taurantoApi.switchPlan(restaurantId,"free");setSubscription(x.subscription);Alert.alert("Plan updated",`Your restaurant is now on ${x.subscription.plans.name}.`)}else{const x=await taurantoApi.startCheckout(restaurantId,id);if(!x.checkoutUrl)throw new Error("Checkout could not be started.");await Linking.openURL(x.checkoutUrl)}}catch(e){Alert.alert(id==="free"?"Could not update plan":"Could not start checkout",e instanceof Error?e.message:"Please retry.")}finally{setBusy("")}};
 if(loading)return <View style={s.loading}><ActivityIndicator color="#168760"/></View>;
 return <ScrollView style={s.page} contentContainerStyle={{paddingTop:inset.top+14,paddingHorizontal:18,paddingBottom:110}}><View style={s.header}><Pressable onPress={onBack} style={s.back}><Ionicons name="arrow-back" size={20}/></Pressable><View><Text style={s.kicker}>ACCOUNT</Text><Text style={s.title}>Plans & billing</Text></View></View><View style={s.status}><Text style={s.statusLabel}>CURRENT PLAN</Text><Text style={s.statusName}>{subscription?.plans?.name||"Free"}</Text><Text style={s.statusCopy}>{subscription?.status||"active"} · Changes are saved to your restaurant subscription.</Text></View><Plan id="free" name="Free" price="$0" current={subscription?.plans?.id==="free"} busy={busy==="free"} onPress={()=>choose("free")} features={["Voice and typed commands","Recent activity","1 restaurant workspace","1 owner account"]}/><Plan id="basic" name="Basic" price="$30" current={subscription?.plans?.id==="basic"} busy={busy==="basic"} onPress={()=>choose("basic")} features={["Everything in Free","Manager approvals","Full activity history","Gmail, Calendar and website","Up to 3 managers"]}/><Plan id="enterprise" name="Enterprise" price="$65" current={subscription?.plans?.id==="enterprise"} busy={busy==="enterprise"} onPress={()=>choose("enterprise")} features={["Everything in Basic","POS and business integrations","Operations directory","Multi-location operations","Advanced audit controls"]}/></ScrollView>
}
function Plan({name,price,current,busy,onPress,features}:any){return <View style={[s.plan,current&&s.currentPlan]}><View style={s.planTop}><View><Text style={s.planName}>{name}</Text><Text><Text style={s.price}>{price}</Text><Text style={s.month}> / month</Text></Text></View>{current?<Text style={s.current}>CURRENT</Text>:null}</View>{features.map((x:string)=><View key={x} style={s.feature}><Ionicons name="checkmark-circle" size={18} color="#168760"/><Text style={s.featureText}>{x}</Text></View>)}<Pressable disabled={current||busy} onPress={onPress} style={[s.button,(current||busy)&&s.disabled]}>{busy?<ActivityIndicator color="#fff"/>:<Text style={s.buttonText}>{current?"Current plan":`Choose ${name}`}</Text>}</Pressable></View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:"#fff"},loading:{flex:1,alignItems:"center",justifyContent:"center",backgroundColor:"#fff"},header:{flexDirection:"row",alignItems:"center",gap:11,marginBottom:17},back:{width:40,height:40,borderRadius:20,borderWidth:1,borderColor:"#DDE4E0",alignItems:"center",justifyContent:"center"},kicker:{fontFamily:"NunitoSans_900Black",fontSize:9.5,letterSpacing:1.5,color:"#168760"},title:{fontFamily:"NunitoSans_900Black",fontSize:27,lineHeight:32,color:"#111613"},status:{borderRadius:18,backgroundColor:"#ECFFF5",borderWidth:1,borderColor:"#C9EEDD",padding:16,marginBottom:14},statusLabel:{fontFamily:"NunitoSans_900Black",fontSize:9,letterSpacing:1.4,color:"#168760"},statusName:{fontFamily:"NunitoSans_900Black",fontSize:22,color:"#111613",marginTop:5},statusCopy:{fontFamily:"NunitoSans_600SemiBold",fontSize:12.5,lineHeight:18,color:"#69716C",marginTop:4,textTransform:"capitalize"},plan:{borderWidth:1,borderColor:"#DDE4E0",borderRadius:19,padding:17,marginBottom:13},currentPlan:{borderColor:"#7DDDB5",backgroundColor:"#FCFFFD"},planTop:{flexDirection:"row",justifyContent:"space-between",marginBottom:14},planName:{fontFamily:"NunitoSans_900Black",fontSize:19,color:"#151A17"},price:{fontFamily:"NunitoSans_900Black",fontSize:27,color:"#174D2E"},month:{fontFamily:"NunitoSans_600SemiBold",fontSize:12,color:"#737B76"},current:{fontFamily:"NunitoSans_900Black",fontSize:8.5,color:"#168760",backgroundColor:"#E7F8EF",paddingHorizontal:9,paddingVertical:6,borderRadius:999},feature:{flexDirection:"row",alignItems:"center",gap:8,marginBottom:9},featureText:{fontFamily:"NunitoSans_700Bold",fontSize:12.5,color:"#434B46"},button:{height:48,borderRadius:13,backgroundColor:"#00D084",alignItems:"center",justifyContent:"center",marginTop:7},buttonText:{fontFamily:"NunitoSans_900Black",fontSize:14,color:"#fff"},disabled:{opacity:.48}});
