import React,{useMemo,useState}from"react";
import{Modal,Pressable,ScrollView,StyleSheet,Text,TextInput,useWindowDimensions,View}from"react-native";
import{Ionicons}from"@expo/vector-icons";
import{LinearGradient}from"expo-linear-gradient";
import{useSafeAreaInsets}from"react-native-safe-area-context";
import{VoiceCommand}from"../lib/models";

type Props={commands:VoiceCommand[];onCommand:(c:VoiceCommand)=>void;onDecide:(id:string,approved:boolean)=>void;onOpenActivity:()=>void;voiceEnabled:boolean;onToggleVoice:()=>void;voiceMode:string;voiceMessage:string};

export function HomeScreen({commands,onOpenActivity,voiceEnabled,onToggleVoice,voiceMode,voiceMessage}:Props){
 const insets=useSafeAreaInsets(),{width}=useWindowDimensions(),wide=width>=768;
 const[searchOpen,setSearchOpen]=useState(false),[alertsOpen,setAlertsOpen]=useState(false),[query,setQuery]=useState("");
 const pending=commands.filter(x=>x.status==="pending"),completed=commands.filter(x=>x.status==="completed"||x.status==="approved");
 const filtered=useMemo(()=>commands.filter(c=>`${c.title} ${c.summary} ${c.transcript}`.toLowerCase().includes(query.toLowerCase())),[commands,query]);
 const live=voiceMode==="recording",working=voiceMode==="working",rate=commands.length?Math.round(completed.length/commands.length*100):100;
 return <>
  <ScrollView style={s.page} contentContainerStyle={[s.content,{maxWidth:wide?980:620,alignSelf:"center",width:"100%"}]}>
   <View style={[s.header,{paddingTop:insets.top+14}]}>
    <View><Text style={s.wordmark}>Tauranto.</Text><Text style={s.brandSub}>RESTAURANT OPERATIONS</Text></View>
    <View style={s.headerActions}><IconButton icon="search" onPress={()=>setSearchOpen(true)}/><IconButton icon="notifications-outline" onPress={()=>setAlertsOpen(true)} badge={pending.length>0}/></View>
   </View>
   <View style={s.canvas}>
    <View style={s.intro}><Text style={s.kicker}>YOUR RESTAURANT, RIGHT NOW</Text><Text style={s.display}>Run the room.{"\n"}<Text style={s.displayAccent}>Just say it.</Text></Text><Text style={s.lead}>Tauranto listens, organizes the work and keeps every action moving.</Text></View>

    <Pressable onPress={onToggleVoice} style={({pressed})=>[s.voiceStage,voiceEnabled&&s.voiceStageOn,pressed&&s.pressed]}>
     <View style={s.dotA}/><View style={s.dotB}/><View style={s.dotC}/>
     <View style={[s.micCircle,voiceEnabled&&s.micCircleOn]}><Ionicons name={live?"mic":"mic-outline"} size={38} color={voiceEnabled?"#123F31":"#173D31"}/></View>
     <View style={s.voiceWords}><Text style={s.voiceEyebrow}>{live?"LISTENING NOW":working?"WORKING":"VOICE COMMAND"}</Text><Text style={s.voiceTitle}>{live?"Go ahead. I’m listening.":working?"Making sense of that…":voiceEnabled?"Tauranto is ready.":"Tap to start talking."}</Text><Text style={s.voiceCopy}>{live?"Speak naturally — no special command format needed.":voiceEnabled?(voiceMessage||"Say “Hey Tauranto” and tell the restaurant what needs to happen."):"Turn on hands-free commands for the floor, kitchen and office."}</Text></View>
     <View style={[s.voiceStatus,voiceEnabled&&s.voiceStatusOn]}><View style={[s.statusDot,voiceEnabled&&s.statusDotOn]}/><Text style={[s.statusText,voiceEnabled&&s.statusTextOn]}>{voiceEnabled?"ON":"OFF"}</Text></View>
    </Pressable>

    <View style={s.snapshotHead}><Text style={s.sectionTitle}>Today</Text><Text style={s.date}>{new Date().toLocaleDateString([],{weekday:"short",month:"short",day:"numeric"})}</Text></View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.statsRail}>
     <Stat value={String(pending.length)} label="Needs approval" tone="coral" onPress={onOpenActivity}/><Stat value={String(completed.length)} label="Completed" tone="green"/><Stat value={`${rate}%`} label="Resolved" tone="gold"/><Stat value={String(commands.length)} label="Commands" tone="ink"/>
    </ScrollView>

    <View style={s.activityHead}><View><Text style={s.sectionTitle}>Recent activity</Text><Text style={s.sectionSub}>The latest things Tauranto heard and handled.</Text></View><Pressable onPress={onOpenActivity} style={s.arrowBtn}><Ionicons name="arrow-forward" size={20} color="#1E2A24"/></Pressable></View>
    <View style={s.activitySheet}>{commands.length===0?<Empty/>:commands.slice(0,5).map((c,i)=><CommandRow key={c.id} c={c} last={i===Math.min(commands.length,5)-1}/>)}</View>
   </View>
  </ScrollView>

  <Modal visible={searchOpen} animationType="slide" onRequestClose={()=>setSearchOpen(false)}><View style={[s.modal,{paddingTop:insets.top+18}]}><ModalHead title="Search" close={()=>setSearchOpen(false)}/><View style={s.searchBox}><Ionicons name="search" size={20} color="#7C776F"/><TextInput autoFocus value={query} onChangeText={setQuery} placeholder="Search commands or actions" placeholderTextColor="#99938A" style={s.searchInput}/></View>{query.length>0&&<ScrollView><View style={s.activitySheet}>{filtered.length?filtered.map((c,i)=><CommandRow key={c.id} c={c} last={i===filtered.length-1}/>):<Text style={s.noResult}>No matching commands.</Text>}</View></ScrollView>}</View></Modal>
  <Modal visible={alertsOpen} animationType="slide" onRequestClose={()=>setAlertsOpen(false)}><View style={[s.modal,{paddingTop:insets.top+18}]}><ModalHead title="Notifications" close={()=>setAlertsOpen(false)}/><Text style={s.noticeIntro}>{pending.length?`${pending.length} command${pending.length===1?" is":"s are"} waiting for approval.`:"You're all caught up."}</Text><View style={s.activitySheet}>{pending.map((c,i)=><Pressable key={c.id} onPress={()=>{setAlertsOpen(false);onOpenActivity()}}><CommandRow c={c} last={i===pending.length-1}/></Pressable>)}</View></View></Modal>
 </>;
}

function IconButton({icon,onPress,badge=false}:{icon:keyof typeof Ionicons.glyphMap;onPress:()=>void;badge?:boolean}){return <Pressable onPress={onPress} style={({pressed})=>[s.iconBtn,pressed&&s.pressed]}><Ionicons name={icon} size={22} color="#1D2923"/>{badge&&<View style={s.alertDot}/>}</Pressable>}
function ModalHead({title,close}:{title:string;close:()=>void}){return <View style={s.modalHead}><Pressable onPress={close} style={s.backBtn}><Ionicons name="arrow-back" size={24} color="#20251F"/></Pressable><Text style={s.modalTitle}>{title}</Text></View>}
function Stat({value,label,tone,onPress}:{value:string;label:string;tone:"coral"|"green"|"gold"|"ink";onPress?:()=>void}){const bg={coral:"#F6C5B5",green:"#CFE0D1",gold:"#F4D98B",ink:"#D9D7D0"}[tone];return <Pressable onPress={onPress} style={({pressed})=>[s.stat,{backgroundColor:bg},pressed&&s.pressed]}><Text style={s.statValue}>{value}</Text><Text style={s.statLabel}>{label}</Text><Ionicons name="arrow-up-outline" size={17} color="#34372F" style={s.statArrow}/></Pressable>}
function Empty(){return <View style={s.empty}><Text style={s.emptyTitle}>Quiet is good.</Text><Text style={s.emptyCopy}>Your first restaurant command will appear here after Tauranto handles it.</Text></View>}
function CommandRow({c,last=false}:{c:VoiceCommand;last?:boolean}){const pending=c.status==="pending";return <View style={[s.row,!last&&s.rowBorder]}><View style={[s.rowBadge,{backgroundColor:pending?"#F7D6CA":"#DDEADD"}]}><Ionicons name={pending?"time-outline":"checkmark"} size={19} color={pending?"#B94F32":"#1D684A"}/></View><View style={s.flex}><Text style={s.rowTitle}>{c.title}</Text><Text style={s.rowMeta}>{pending?"Pending approval":"Completed"} · {new Date(c.createdAt).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}</Text></View><Ionicons name="chevron-forward" size={18} color="#9B958C"/></View>}

const s=StyleSheet.create({
 page:{flex:1,backgroundColor:"#F7F7F2"},content:{paddingBottom:118},canvas:{paddingHorizontal:22,paddingTop:28},flex:{flex:1},pressed:{opacity:.84,transform:[{scale:.985}]},
 header:{minHeight:86,paddingHorizontal:22,paddingBottom:13,flexDirection:"row",alignItems:"flex-end",justifyContent:"space-between",backgroundColor:"#F7F7F2"},wordmark:{fontFamily:"NunitoSans_900Black",fontSize:25,color:"#183B30",letterSpacing:-1},brandSub:{fontFamily:"NunitoSans_800ExtraBold",fontSize:8,letterSpacing:1.5,color:"#A36A50",marginTop:1},headerActions:{flexDirection:"row",gap:8},iconBtn:{width:42,height:42,borderRadius:21,backgroundColor:"#FFFFFF",alignItems:"center",justifyContent:"center",shadowColor:"#5C4A3B",shadowOpacity:.08,shadowRadius:10,shadowOffset:{width:0,height:4},elevation:2},alertDot:{position:"absolute",right:8,top:7,width:8,height:8,borderRadius:4,backgroundColor:"#DE6244",borderWidth:2,borderColor:"#FFFFFF"},
 intro:{paddingTop:3,paddingBottom:24},kicker:{fontFamily:"NunitoSans_900Black",fontSize:10,letterSpacing:1.8,color:"#7B756C"},display:{fontFamily:"NunitoSans_900Black",fontSize:wideFont(47),lineHeight:52,color:"#171C18",letterSpacing:-2,marginTop:8},displayAccent:{color:"#CF654A"},lead:{fontFamily:"NunitoSans_700Bold",fontSize:14,lineHeight:21,color:"#777269",maxWidth:480,marginTop:11},
 voiceStage:{minHeight:260,borderRadius:34,backgroundColor:"#12533F",padding:22,overflow:"hidden",justifyContent:"flex-end",shadowColor:"#173F33",shadowOpacity:.18,shadowRadius:22,shadowOffset:{width:0,height:10},elevation:4},voiceStageOn:{backgroundColor:"#0D6248"},dotA:{position:"absolute",width:24,height:24,borderRadius:12,backgroundColor:"#E8876D",right:40,top:27},dotB:{position:"absolute",width:15,height:15,borderRadius:8,backgroundColor:"#F0C96F",right:112,top:63},dotC:{position:"absolute",width:11,height:11,borderRadius:6,backgroundColor:"#A8C8B9",right:74,top:108},micCircle:{position:"absolute",right:28,top:50,width:92,height:92,borderRadius:46,backgroundColor:"#FFFFFF",alignItems:"center",justifyContent:"center",shadowColor:"#0B2D24",shadowOpacity:.18,shadowRadius:16,shadowOffset:{width:0,height:7},elevation:4},micCircleOn:{backgroundColor:"#FFFFFF"},voiceWords:{maxWidth:"74%"},voiceEyebrow:{fontFamily:"NunitoSans_900Black",fontSize:9,letterSpacing:1.5,color:"#F0C96F"},voiceTitle:{fontFamily:"NunitoSans_900Black",fontSize:25,lineHeight:30,color:"#FFFFFF",letterSpacing:-.7,marginTop:4},voiceCopy:{fontFamily:"NunitoSans_700Bold",fontSize:12,lineHeight:18,color:"#D9E7E1",marginTop:6},voiceStatus:{position:"absolute",right:17,bottom:17,flexDirection:"row",alignItems:"center",gap:5,backgroundColor:"#FFFFFF",paddingHorizontal:10,paddingVertical:6,borderRadius:999},voiceStatusOn:{backgroundColor:"#FFFFFF"},statusDot:{width:6,height:6,borderRadius:3,backgroundColor:"#B76C55"},statusDotOn:{backgroundColor:"#27905F"},statusText:{fontFamily:"NunitoSans_900Black",fontSize:8,letterSpacing:1,color:"#315B4C"},statusTextOn:{color:"#236747"},
 snapshotHead:{flexDirection:"row",justifyContent:"space-between",alignItems:"flex-end",marginTop:34,marginBottom:13},sectionTitle:{fontFamily:"NunitoSans_900Black",fontSize:26,color:"#191E1A",letterSpacing:-.8},date:{fontFamily:"NunitoSans_800ExtraBold",fontSize:11,color:"#918A80"},statsRail:{gap:11,paddingRight:20},stat:{width:142,height:130,borderRadius:27,padding:16,justifyContent:"flex-end"},statValue:{fontFamily:"NunitoSans_900Black",fontSize:35,color:"#20251F",letterSpacing:-1.4},statLabel:{fontFamily:"NunitoSans_800ExtraBold",fontSize:11,color:"#595B54",marginTop:1},statArrow:{position:"absolute",right:15,top:15,transform:[{rotate:"45deg"}]},
 activityHead:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginTop:36,marginBottom:13},sectionSub:{fontFamily:"NunitoSans_700Bold",fontSize:11,color:"#8B857C",marginTop:3},arrowBtn:{width:43,height:43,borderRadius:22,backgroundColor:"#DCE8E1",alignItems:"center",justifyContent:"center"},activitySheet:{backgroundColor:"#FFFFFF",borderRadius:28,paddingHorizontal:17,shadowColor:"#5E4A38",shadowOpacity:.07,shadowRadius:18,shadowOffset:{width:0,height:7},elevation:2},row:{minHeight:82,flexDirection:"row",alignItems:"center",gap:12},rowBorder:{borderBottomWidth:1,borderBottomColor:"#EEEDE8"},rowBadge:{width:42,height:42,borderRadius:21,alignItems:"center",justifyContent:"center"},rowTitle:{fontFamily:"NunitoSans_900Black",fontSize:14,color:"#242923"},rowMeta:{fontFamily:"NunitoSans_700Bold",fontSize:11,color:"#8B867D",marginTop:4},empty:{paddingVertical:31,paddingHorizontal:8},emptyTitle:{fontFamily:"NunitoSans_900Black",fontSize:20,color:"#242923"},emptyCopy:{fontFamily:"NunitoSans_700Bold",fontSize:12,lineHeight:19,color:"#888177",marginTop:5,maxWidth:320},
 modal:{flex:1,backgroundColor:"#F7F7F2",paddingHorizontal:22},modalHead:{height:66,flexDirection:"row",alignItems:"center",gap:14},backBtn:{width:42,height:42,borderRadius:21,backgroundColor:"#FFFFFF",alignItems:"center",justifyContent:"center"},modalTitle:{fontFamily:"NunitoSans_900Black",fontSize:27,color:"#1C211D"},searchBox:{height:57,borderRadius:29,backgroundColor:"#FFFFFF",flexDirection:"row",alignItems:"center",paddingHorizontal:17,gap:10,marginBottom:16},searchInput:{flex:1,fontFamily:"NunitoSans_700Bold",fontSize:15,color:"#1D211D"},noResult:{fontFamily:"NunitoSans_700Bold",fontSize:14,color:"#817A71",paddingVertical:35,textAlign:"center"},noticeIntro:{fontFamily:"NunitoSans_700Bold",fontSize:14,color:"#746E65",marginVertical:13}
});
function wideFont(n:number){return n;}
