import React,{useEffect,useState}from"react";
import{ActivityIndicator,Alert,Image,Platform,Pressable,ScrollView,StyleSheet,Text,TextInput,View}from"react-native";
import{Ionicons}from"@expo/vector-icons";
import{useSafeAreaInsets}from"react-native-safe-area-context";
import{taurantoApi,supabase}from"../lib/api";
import{colors}from"../theme/tokens";
import{IntegrationsScreen}from"./IntegrationsScreen";

export function ProfileHub({restaurantId,initialPage="profile",onBack}:{restaurantId:string;initialPage?:"profile"|"integrations";onBack:()=>void}){const[page]=useState<"profile"|"integrations">(initialPage);if(page==="profile")return <ProfileScreen restaurantId={restaurantId}/>;return <View style={s.hub}><View style={s.hubTop}><Pressable accessibilityLabel="Go back" onPress={onBack} style={s.hubBack}><Ionicons name="arrow-back" size={21} color={colors.ink}/></Pressable><Text style={s.hubTitle}>Integrations</Text></View><View style={{flex:1}}><IntegrationsScreen restaurantId={restaurantId}/></View></View>}

export function ProfileScreen({restaurantId}:{restaurantId:string}){
 const inset=useSafeAreaInsets(),[ws,setWs]=useState<any>(null),[name,setName]=useState(""),[restaurant,setRestaurant]=useState(""),[avatar,setAvatar]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[dark,setDark]=useState(false),[themeBusy,setThemeBusy]=useState(false);
 const load=async()=>{setLoading(true);try{const x=await taurantoApi.workspace(restaurantId);setWs(x);setName(x?.profile?.full_name||"");setRestaurant(x?.restaurant?.name||"");setAvatar(x?.profile?.avatar_url||x?.restaurant?.logo_url||"");setDark(x?.preferences?.appearance==="dark")}catch(e){Alert.alert("Profile unavailable",e instanceof Error?e.message:"Please retry.")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[restaurantId]);
 const choose=(file?:File)=>{if(!file)return;if(file.size>2_000_000)return Alert.alert("Photo too large","Choose an image smaller than 2 MB.");const reader=new FileReader();reader.onload=()=>setAvatar(String(reader.result||""));reader.readAsDataURL(file)};
 const save=async()=>{if(!name.trim()||!restaurant.trim())return Alert.alert("Required","Add your name and restaurant name.");setSaving(true);try{await taurantoApi.updateWorkspace(restaurantId,{profile:{...(ws?.profile||{}),full_name:name.trim(),avatar_url:avatar||null},restaurant:{...(ws?.restaurant||{}),name:restaurant.trim(),logo_url:avatar||null},preferences:ws?.preferences||{}});Alert.alert("Profile saved","Your name, restaurant and photo have been updated.")}catch(e){Alert.alert("Could not save",e instanceof Error?e.message:"Please retry.")}finally{setSaving(false)}};
 const toggleTheme=async()=>{if(themeBusy)return;const next=!dark,preferences={...(ws?.preferences||{}),appearance:next?"dark":"light"};setDark(next);setThemeBusy(true);try{await taurantoApi.updateWorkspace(restaurantId,{profile:ws?.profile||{},restaurant:ws?.restaurant||{},preferences});setWs((x:any)=>({...x,preferences}))}catch(e){setDark(!next);Alert.alert("Appearance not saved",e instanceof Error?e.message:"Please retry.")}finally{setThemeBusy(false)}};
 if(loading)return <View style={s.loading}><ActivityIndicator color={colors.leaf}/></View>;
 return <ScrollView style={s.page} showsVerticalScrollIndicator={false} contentContainerStyle={{paddingTop:inset.top+18,paddingHorizontal:18,paddingBottom:135,maxWidth:570,alignSelf:"center",width:"100%"}}>
  <Text style={s.kicker}>YOUR ACCOUNT</Text><Text style={s.title}>Profile</Text><Text style={s.copy}>Add the name and photo your team should see across Tauranto.</Text>
  <View style={s.card}>
   <View style={s.photoRow}><View style={s.photo}>{avatar?<Image source={{uri:avatar}} style={s.photoImage}/>:<Ionicons name="restaurant-outline" size={36} color={colors.leafDeep}/>}<WebFileInput onFile={choose}/></View><View style={{flex:1}}><Text style={s.photoTitle}>Restaurant photo</Text><Text style={s.photoCopy}>Tap the circle to upload a JPG or PNG.</Text></View></View>
   <Text style={s.label}>Your name</Text><TextInput value={name} onChangeText={setName} placeholder="Your name" placeholderTextColor="#929A95" style={s.input}/>
   <Text style={s.label}>Restaurant name</Text><TextInput value={restaurant} onChangeText={setRestaurant} placeholder="Restaurant name" placeholderTextColor="#929A95" style={s.input}/>
   <Pressable disabled={saving} onPress={save} style={({pressed})=>[s.save,pressed&&{opacity:.86},saving&&{opacity:.6}]}>{saving?<ActivityIndicator color="#fff"/>:<Text style={s.saveText}>Save profile</Text>}</Pressable>
  </View>
  <View style={s.profileActions}><Pressable onPress={()=>supabase.auth.signOut()} style={s.logout}><Ionicons name="log-out-outline" size={20} color="#9B3F36"/><Text style={s.logoutText}>Log out</Text></Pressable><Pressable accessibilityLabel={dark?"Switch to light appearance":"Switch to dark appearance"} disabled={themeBusy} onPress={toggleTheme} style={[s.themeButton,dark&&s.themeButtonDark]}><Ionicons name={dark?"sunny-outline":"moon-outline"} size={24} color={dark?"#F1B94B":colors.ink}/></Pressable></View>
 </ScrollView>
}

function WebFileInput({onFile}:{onFile:(file?:File)=>void}){if(Platform.OS!=="web")return null;return React.createElement("input",{type:"file",accept:"image/jpeg,image/png,image/webp",onChange:(e:any)=>onFile(e.target.files?.[0]),style:{position:"absolute",inset:0,width:"100%",height:"100%",opacity:0,cursor:"pointer"},"aria-label":"Upload restaurant photo"} as any)}

const s=StyleSheet.create({hub:{flex:1,backgroundColor:"#fff"},hubTop:{height:58,paddingHorizontal:16,borderBottomWidth:1,borderBottomColor:"#E0E5E3",flexDirection:"row",alignItems:"center",gap:10},hubBack:{width:38,height:38,borderRadius:19,borderWidth:1,borderColor:"#DCE3DF",alignItems:"center",justifyContent:"center"},hubTitle:{fontFamily:"NunitoSans_900Black",fontSize:15,color:colors.ink},loading:{flex:1,alignItems:"center",justifyContent:"center",backgroundColor:"#fff"},page:{flex:1,backgroundColor:"#fff"},kicker:{fontFamily:"NunitoSans_900Black",fontSize:10,letterSpacing:2,color:colors.leafDeep},title:{fontFamily:"NunitoSans_900Black",fontSize:31,lineHeight:37,color:colors.ink,letterSpacing:-1,marginTop:5},copy:{fontFamily:"NunitoSans_600SemiBold",fontSize:14,lineHeight:20,color:colors.muted,marginTop:5,marginBottom:17},card:{borderWidth:1.3,borderColor:"#DCE3DF",borderRadius:23,backgroundColor:"#fff",padding:17,shadowColor:"#18231E",shadowOpacity:.06,shadowRadius:16,shadowOffset:{width:0,height:7},elevation:2},photoRow:{flexDirection:"row",alignItems:"center",gap:14,marginBottom:19},photo:{width:76,height:76,borderRadius:38,borderWidth:1.5,borderColor:"#BEEBD7",backgroundColor:"#F0FFF8",alignItems:"center",justifyContent:"center",overflow:"hidden",position:"relative"},photoImage:{width:"100%",height:"100%"},photoTitle:{fontFamily:"NunitoSans_900Black",fontSize:17,color:colors.ink},photoCopy:{fontFamily:"NunitoSans_600SemiBold",fontSize:11,lineHeight:16,color:colors.muted,marginTop:4},label:{fontFamily:"NunitoSans_800ExtraBold",fontSize:11,color:"#4E5852",marginBottom:6},input:{height:48,borderRadius:13,borderWidth:1.2,borderColor:"#CDD6D1",paddingHorizontal:13,fontFamily:"NunitoSans_800ExtraBold",fontSize:14,color:colors.ink,marginBottom:14,backgroundColor:"#fff"},save:{height:49,borderRadius:14,backgroundColor:colors.leaf,alignItems:"center",justifyContent:"center",marginTop:2},saveText:{fontFamily:"NunitoSans_900Black",fontSize:15,color:"#fff"},profileActions:{flexDirection:"row",alignItems:"center",gap:10,marginTop:17},logout:{height:51,flex:1,borderRadius:15,borderWidth:1,borderColor:"#F0D7D2",backgroundColor:"#FFF7F5",flexDirection:"row",alignItems:"center",justifyContent:"center",gap:8},logoutText:{fontFamily:"NunitoSans_900Black",fontSize:14,color:"#9B3F36"},themeButton:{width:51,height:51,borderRadius:16,borderWidth:1,borderColor:"#DCE3DF",backgroundColor:"#fff",alignItems:"center",justifyContent:"center"},themeButtonDark:{backgroundColor:"#202722",borderColor:"#364139"}});
