import React from "react";
import {ActivityIndicator,Pressable,StyleSheet,Text,TextInput,View} from "react-native";
import {SafeAreaView} from "react-native-safe-area-context";
import {Ionicons} from "@expo/vector-icons";
import {supabase,taurantoApi} from "../lib/api";
import {colors} from "../theme/tokens";

type Band="0-100"|"100-300"|"300-500"|"500-1000+";
const bands:Band[]=["0-100","100-300","300-500","500-1000+"];
export function WorkspaceRecoveryScreen({message,onRetry}:{message?:string;onRetry:()=>void}){
  const missing=message==="NO_RESTAURANT_MEMBERSHIP"||message?.includes("not connected to an active restaurant");
  const [busy,setBusy]=React.useState(false),[name,setName]=React.useState(""),[band,setBand]=React.useState<Band>("0-100"),[error,setError]=React.useState("");
  const signOut=async()=>{setBusy(true);try{await supabase.auth.signOut()}finally{setBusy(false)}};
  const create=async()=>{const clean=name.trim();if(clean.length<2){setError("Enter your restaurant name.");return}setBusy(true);setError("");try{await taurantoApi.onboard(clean,band);onRetry()}catch(e){setError(e instanceof Error?e.message:"We could not create your restaurant workspace.")}finally{setBusy(false)}};
  if(missing)return <SafeAreaView style={s.page}><View style={s.card}><View style={s.icon}><Ionicons name="restaurant-outline" size={28} color={colors.leafDeep}/></View><Text style={s.title}>Set up your restaurant</Text><Text style={s.copy}>Your Tauranto account is ready. Create your restaurant workspace to continue.</Text><Text style={s.label}>Restaurant name</Text><TextInput value={name} onChangeText={setName} placeholder="e.g. Harbor Kitchen" placeholderTextColor="#98A198" style={s.input}/><Text style={s.label}>Approximate daily diners</Text><View style={s.bands}>{bands.map(x=><Pressable key={x} onPress={()=>setBand(x)} style={[s.band,band===x&&s.bandActive]}><Text style={[s.bandText,band===x&&s.bandTextActive]}>{x}</Text></Pressable>)}</View>{!!error&&<Text style={s.error}>{error}</Text>}<Pressable disabled={busy} onPress={create} style={[s.primary,busy&&s.disabled]}>{busy?<ActivityIndicator color="#fff"/>:<Text style={s.primaryText}>Create restaurant workspace</Text>}</Pressable><Pressable disabled={busy} onPress={signOut} style={s.secondary}><Text style={s.secondaryText}>Sign out</Text></Pressable></View></SafeAreaView>;
  return <SafeAreaView style={s.page}><View style={s.card}><View style={s.icon}><Ionicons name="restaurant-outline" size={28} color={colors.leafDeep}/></View><Text style={s.title}>We couldn't open your restaurant workspace.</Text><Text style={s.copy}>{message||"Tauranto could not load your restaurant workspace."}</Text><Pressable disabled={busy} onPress={onRetry} style={s.primary}><Text style={s.primaryText}>Try again</Text></Pressable><Pressable disabled={busy} onPress={signOut} style={s.secondary}>{busy?<ActivityIndicator color={colors.leafDeep}/>:<Text style={s.secondaryText}>Sign out and use another account</Text>}</Pressable></View></SafeAreaView>;
}
const s=StyleSheet.create({page:{flex:1,alignItems:"center",justifyContent:"center",padding:22,backgroundColor:colors.cream},card:{width:"100%",maxWidth:460,padding:24,borderRadius:24,backgroundColor:"#fff",borderWidth:1,borderColor:colors.line},icon:{width:54,height:54,borderRadius:17,alignItems:"center",justifyContent:"center",backgroundColor:colors.leafPale,marginBottom:18},title:{fontFamily:"NunitoSans_900Black",fontSize:24,lineHeight:30,color:colors.ink,marginBottom:10},copy:{fontFamily:"NunitoSans_600SemiBold",fontSize:14,lineHeight:21,color:colors.muted,marginBottom:20},label:{fontFamily:"NunitoSans_900Black",fontSize:12,color:colors.inkSoft,marginBottom:7},input:{height:54,borderWidth:1,borderColor:colors.line,borderRadius:14,paddingHorizontal:14,fontFamily:"NunitoSans_700Bold",fontSize:15,color:colors.ink,marginBottom:17,backgroundColor:"#FBFCF9"},bands:{flexDirection:"row",flexWrap:"wrap",gap:8,marginBottom:18},band:{paddingHorizontal:12,height:38,borderRadius:12,borderWidth:1,borderColor:colors.line,alignItems:"center",justifyContent:"center"},bandActive:{backgroundColor:colors.leafInk,borderColor:colors.leafInk},bandText:{fontFamily:"NunitoSans_800ExtraBold",fontSize:11,color:colors.inkSoft},bandTextActive:{color:"#fff"},error:{fontFamily:"NunitoSans_700Bold",fontSize:12,lineHeight:18,color:"#A33F29",marginBottom:12},primary:{height:54,borderRadius:15,alignItems:"center",justifyContent:"center",backgroundColor:colors.leafInk,marginBottom:10},primaryText:{fontFamily:"NunitoSans_900Black",fontSize:14,color:"#fff"},secondary:{height:50,borderRadius:15,alignItems:"center",justifyContent:"center",borderWidth:1,borderColor:colors.line},secondaryText:{fontFamily:"NunitoSans_900Black",fontSize:13,color:colors.leafDeep},disabled:{opacity:.6}});