import React,{useEffect,useState} from 'react';
import {View,Text,TextInput,Pressable,ScrollView,StyleSheet,Switch,ActivityIndicator,Alert} from 'react-native';
import {Ionicons} from '@expo/vector-icons';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import {taurantoApi} from '../lib/api';
import {workspaceApi} from '../lib/workspaceApi';
import {SettingsPanel} from './SettingsPanel';
export type WorkspacePage='profile'|'team'|'notifications'|'settings'|'security'|'help';
export function WorkspaceScreen({restaurantId,page,onBack}:{restaurantId:string;page:WorkspacePage;onBack:()=>void}){
 const inset=useSafeAreaInsets(),[ws,setWs]=useState<any>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[invite,setInvite]=useState({name:'',email:'',phone:''}),[departments,setDepartments]=useState<any[]>([]),[dept,setDept]=useState({name:'',description:'',memberIds:[] as string[]}),[tickets,setTickets]=useState<any[]>([]),[support,setSupport]=useState({email:'',subject:'',message:''});
 const load=async()=>{setLoading(true);try{const workspace=await taurantoApi.workspace(restaurantId);setWs(workspace);setSupport(p=>({...p,email:p.email||workspace.profile?.email||''}));if(page==='team')setDepartments((await workspaceApi.departments(restaurantId)).departments||[]);if(page==='help')setTickets((await workspaceApi.supportRequests(restaurantId)).requests||[])}catch(e){Alert.alert('Could not load',e instanceof Error?e.message:'Please retry.')}finally{setLoading(false)}};useEffect(()=>{void load()},[restaurantId,page]);
 const save=async()=>{setSaving(true);try{await taurantoApi.updateWorkspace(restaurantId,{profile:ws.profile,restaurant:ws.restaurant,preferences:ws.preferences});Alert.alert('Saved','These settings are now stored in your restaurant database.')}catch(e){Alert.alert('Could not save',e instanceof Error?e.message:'Please retry.')}finally{setSaving(false)}};
 const pref=(group:string,key:string,value:any)=>setWs((p:any)=>({...p,preferences:group==='root'?{...p.preferences,[key]:value}:{...p.preferences,[group]:{...p.preferences?.[group],[key]:value}}}));const field=(group:'profile'|'restaurant',key:string,value:string)=>setWs((p:any)=>({...p,[group]:{...p[group],[key]:value}}));
 const addManager=async()=>{if(!invite.name.trim()||!invite.email.trim())return Alert.alert('Required','Name and email are required.');try{await taurantoApi.inviteManager(restaurantId,invite.name.trim(),invite.email.trim(),invite.phone.trim());setInvite({name:'',email:'',phone:''});await load();Alert.alert('Invitation saved','The manager invitation is stored for this restaurant.')}catch(e){Alert.alert('Could not add manager',e instanceof Error?e.message:'Please retry.')}};
 const createDepartment=async()=>{if(!dept.name.trim())return Alert.alert('Required','Department name is required.');setSaving(true);try{await workspaceApi.createDepartment(restaurantId,dept.name.trim(),dept.description.trim(),dept.memberIds);setDept({name:'',description:'',memberIds:[]});await load();Alert.alert('Department created','Tauranto can now resolve commands addressed to this department.')}catch(e){Alert.alert('Could not create department',e instanceof Error?e.message:'Please retry.')}finally{setSaving(false)}};
 const sendSupport=async()=>{if(!support.email.trim()||!support.subject.trim()||!support.message.trim())return Alert.alert('Required','Email, subject, and message are required.');setSaving(true);try{const result=await workspaceApi.createSupportRequest(restaurantId,support.email.trim(),support.subject.trim(),support.message.trim());setSupport(p=>({...p,subject:'',message:''}));await load();Alert.alert('Request received',result.emailSent?'Your request was saved and emailed to support.':'Your request was saved for the support team.')}catch(e){Alert.alert('Could not send request',e instanceof Error?e.message:'Please retry.')}finally{setSaving(false)}};
 if(loading||!ws)return <View style={s.loading}><ActivityIndicator color='#287345'/></View>;const title={profile:'Profile & restaurant',team:'Team & departments',notifications:'Notifications',settings:'Settings',security:'Security & privacy',help:'Help & support'}[page];
 return <ScrollView style={s.page} contentContainerStyle={{paddingTop:inset.top+14,paddingHorizontal:20,paddingBottom:110}}><View style={s.top}><Pressable onPress={onBack} style={s.back}><Ionicons name='arrow-back' size={22}/></Pressable><View><Text style={s.kicker}>TAURANTO WORKSPACE</Text><Text style={s.title}>{title}</Text></View></View>
 {page==='profile'&&<><Label t='Your name *'/><Input v={ws.profile?.full_name} c={(x:string)=>field('profile','full_name',x)}/><Label t='Your phone *'/><Input v={ws.profile?.phone} c={(x:string)=>field('profile','phone',x)} keyboard='phone-pad'/><Label t='Restaurant name *'/><Input v={ws.restaurant?.name} c={(x:string)=>field('restaurant','name',x)}/><Label t='Restaurant phone *'/><Input v={ws.restaurant?.phone} c={(x:string)=>field('restaurant','phone',x)} keyboard='phone-pad'/><Label t='Website *'/><Input v={ws.restaurant?.website} c={(x:string)=>field('restaurant','website',x)} keyboard='url'/><Label t='Address *'/><Input v={ws.restaurant?.address} c={(x:string)=>field('restaurant','address',x)}/><Label t='Timezone'/><Input v={ws.restaurant?.timezone} c={(x:string)=>field('restaurant','timezone',x)}/><Save busy={saving} onPress={save}/></>}
 {page==='team'&&<><Text style={s.copy}>Create people and departments so commands such as “notify all chefs” resolve to real recipients.</Text><Text style={s.sub}>ACTIVE PEOPLE</Text>{(ws.members||[]).map((m:any)=><View key={m.user_id} style={s.card}><View style={{flex:1}}><Text style={s.cardTitle}>{m.profiles?.full_name||m.profiles?.email||'Team member'}</Text><Text style={s.meta}>{m.profiles?.email} · {m.role}</Text></View><Text style={s.badge}>{m.can_approve?'APPROVER':'MEMBER'}</Text></View>)}<Text style={s.sub}>DEPARTMENTS</Text>{departments.length===0&&<Text style={s.copy}>No departments yet. Create your first one below.</Text>}{departments.map((d:any)=><View key={d.id} style={s.card}><View style={{flex:1}}><Text style={s.cardTitle}>{d.name}</Text><Text style={s.meta}>{d.description||'No description'} · {(d.department_members||[]).length} members</Text></View></View>)}<Text style={s.sub}>CREATE DEPARTMENT</Text><Input v={dept.name} c={(x:string)=>setDept(p=>({...p,name:x}))} placeholder='e.g. Chefs'/><Input v={dept.description} c={(x:string)=>setDept(p=>({...p,description:x}))} placeholder='What this group handles'/>{(ws.members||[]).map((m:any)=>{const selected=dept.memberIds.includes(m.user_id);return <Pressable key={m.user_id} onPress={()=>setDept(p=>({...p,memberIds:selected?p.memberIds.filter(x=>x!==m.user_id):[...p.memberIds,m.user_id]}))} style={s.memberChoice}><Ionicons name={selected?'checkbox':'square-outline'} size={22} color={selected?'#00B873':'#8A938D'}/><Text style={s.toggleText}>{m.profiles?.full_name||m.profiles?.email}</Text></Pressable>})}<Pressable disabled={saving} onPress={createDepartment} style={s.primary}><Text style={s.primaryText}>Create department</Text></Pressable><Text style={s.sub}>INVITE MANAGER</Text><Input v={invite.name} c={(x:string)=>setInvite(p=>({...p,name:x}))} placeholder='Full name'/><Input v={invite.email} c={(x:string)=>setInvite(p=>({...p,email:x}))} placeholder='Email' keyboard='email-address'/><Input v={invite.phone} c={(x:string)=>setInvite(p=>({...p,phone:x}))} placeholder='Phone' keyboard='phone-pad'/><Pressable onPress={addManager} style={s.primary}><Text style={s.primaryText}>Save manager invitation</Text></Pressable></>}
 {page==='notifications'&&<><Toggle title='Approval requests by email' value={!!ws.preferences?.notifications?.approval_email} onChange={(v:boolean)=>pref('notifications','approval_email',v)}/><Text style={s.copy}>This setting controls real approval email delivery. In-app activity remains recorded in the audit timeline.</Text><Save busy={saving} onPress={save}/></>}{page==='settings'&&<SettingsPanel preferences={ws.preferences} onPreference={pref} onSave={save} saving={saving}/>} {page==='security'&&<><Text style={s.copy}>Command audio is processed transiently and is not retained. Operational events remain available for the period below.</Text><Label t='Activity retention (days)'/><Input v={String(ws.preferences?.privacy?.activity_retention_days||90)} c={(x:string)=>pref('privacy','activity_retention_days',Math.max(1,Number(x)||90))} keyboard='number-pad'/><Save busy={saving} onPress={save}/></>}
 {page==='help'&&<><View style={s.health}><Ionicons name='shield-checkmark-outline' size={24} color='#287345'/><View><Text style={s.cardTitle}>Database-backed support</Text><Text style={s.meta}>Every submission is stored against {ws.restaurant?.name}.</Text></View></View><Label t='Reply email *'/><Input v={support.email} c={(x:string)=>setSupport(p=>({...p,email:x}))} keyboard='email-address'/><Label t='Subject *'/><Input v={support.subject} c={(x:string)=>setSupport(p=>({...p,subject:x}))} placeholder='What do you need help with?'/><Label t='Message *'/><TextInput multiline value={support.message} onChangeText={(x:string)=>setSupport(p=>({...p,message:x}))} placeholder='Describe the issue and what you expected.' placeholderTextColor='#9AA19B' style={[s.input,s.message]}/><Save busy={saving} onPress={sendSupport}/><Text style={s.sub}>RECENT REQUESTS</Text>{tickets.length===0?<Text style={s.copy}>No support requests yet.</Text>:tickets.map((t:any)=><View key={t.id} style={s.card}><View><Text style={s.cardTitle}>{t.subject}</Text><Text style={s.meta}>{t.status.replace('_',' ')} · {new Date(t.created_at).toLocaleDateString()}</Text></View></View>)}</>}
 </ScrollView>}
function Label({t}:{t:string}){return <Text style={s.label}>{t}</Text>}function Input({v,c,placeholder,keyboard}:any){return <TextInput value={v||''} onChangeText={c} placeholder={placeholder} keyboardType={keyboard} placeholderTextColor='#9AA19B' style={s.input}/>}function Toggle({title,value,onChange}:any){return <View style={s.toggle}><Text style={s.toggleText}>{title}</Text><Switch value={value} onValueChange={onChange}/></View>}function Save({busy,onPress}:any){return <Pressable disabled={busy} onPress={onPress} style={s.primary}>{busy?<ActivityIndicator color='white'/>:<Text style={s.primaryText}>Save changes</Text>}</Pressable>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#FAFBF9'},loading:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#FAFBF9'},top:{flexDirection:'row',alignItems:'center',gap:12,marginBottom:20},back:{width:44,height:44,borderRadius:14,backgroundColor:'white',borderWidth:1,borderColor:'#E5EAE5',alignItems:'center',justifyContent:'center'},kicker:{fontFamily:'NunitoSans_900Black',fontSize:10,letterSpacing:1.2,color:'#287345'},title:{fontFamily:'NunitoSans_900Black',fontSize:29,lineHeight:35,color:'#1E2420',marginTop:2},label:{fontFamily:'NunitoSans_900Black',fontSize:12,color:'#4D574E',marginTop:14,marginBottom:7},input:{minHeight:50,borderRadius:14,borderWidth:1,borderColor:'#DEE5DF',backgroundColor:'white',paddingHorizontal:14,fontFamily:'NunitoSans_700Bold',fontSize:14,color:'#1E2420',marginBottom:4},message:{height:130,textAlignVertical:'top',paddingTop:14},primary:{height:52,borderRadius:14,backgroundColor:'#00C982',alignItems:'center',justifyContent:'center',marginTop:20},primaryText:{fontFamily:'NunitoSans_900Black',fontSize:14,color:'white'},copy:{fontFamily:'NunitoSans_700Bold',fontSize:14,lineHeight:20,color:'#6F786F',marginBottom:14},toggle:{minHeight:64,backgroundColor:'white',borderWidth:1,borderColor:'#E5EAE5',borderRadius:15,paddingHorizontal:15,marginBottom:10,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},toggleText:{fontFamily:'NunitoSans_800ExtraBold',fontSize:14,color:'#29302A',flex:1,paddingRight:12},memberChoice:{minHeight:52,backgroundColor:'white',borderWidth:1,borderColor:'#E5EAE5',borderRadius:14,paddingHorizontal:14,marginBottom:8,flexDirection:'row',gap:10,alignItems:'center'},card:{minHeight:68,backgroundColor:'white',borderWidth:1,borderColor:'#E5EAE5',borderRadius:15,padding:14,marginBottom:10,flexDirection:'row',alignItems:'center'},cardTitle:{fontFamily:'NunitoSans_900Black',fontSize:15,color:'#1E2420'},meta:{fontFamily:'NunitoSans_600SemiBold',fontSize:11.5,color:'#737C74',marginTop:4},badge:{fontFamily:'NunitoSans_900Black',fontSize:9,color:'#287345',backgroundColor:'#EAF4EC',padding:7,borderRadius:8},sub:{fontFamily:'NunitoSans_900Black',fontSize:11,letterSpacing:1,color:'#687169',marginTop:20,marginBottom:8},health:{backgroundColor:'#EEF7F0',borderRadius:16,padding:16,flexDirection:'row',gap:12,alignItems:'center',marginBottom:12}});
