import type {VercelRequest,VercelResponse} from "@vercel/node";import {admin,fail,requireUser} from "../../server/http";import {signState} from "../../server/credentials";
const providers=["gmail","google_calendar","slack","hubspot","square"] as const;type Provider=typeof providers[number];
function callbackUrl(req:VercelRequest){const configured=process.env.PUBLIC_API_URL?.replace(/\/$/,"");if(configured)return `${configured}/api/integrations/oauth-callback`;const proto=String(req.headers["x-forwarded-proto"]||"https"),host=String(req.headers["x-forwarded-host"]||req.headers.host||"");return `${proto}://${host}/api/integrations/oauth-callback`}
export default async function handler(req:VercelRequest,res:VercelResponse){if(req.method!=="POST")return res.status(405).json({error:"METHOD_NOT_ALLOWED"});try{const user=await requireUser(req),restaurantId=String(req.body?.restaurantId||""),provider=String(req.body?.provider||"") as Provider;if(!providers.includes(provider))throw new Error("UNSUPPORTED_PROVIDER");const db=admin(),{data:member}=await db.from("restaurant_members").select("role").eq("restaurant_id",restaurantId).eq("user_id",user.id).eq("active",true).maybeSingle();if(!member||!["owner","admin"].includes(member.role))throw new Error("FORBIDDEN");const redirectUri=callbackUrl(req),state=signState({restaurantId,provider,userId:user.id,exp:Date.now()+10*60*1000});let authorizationUrl="";
if(provider==="gmail"||provider==="google_calendar"){const clientId=process.env.GOOGLE_CLIENT_ID;if(!clientId)throw new Error("GOOGLE_CLIENT_ID_NOT_CONFIGURED");const scope=provider==="gmail"?["openid","email","https://www.googleapis.com/auth/gmail.send"]:["openid","email","https://www.googleapis.com/auth/calendar.events","https://www.googleapis.com/auth/calendar.readonly"];authorizationUrl=`https://accounts.google.com/o/oauth2/v2/auth?${new URLSearchParams({client_id:clientId,redirect_uri:redirectUri,response_type:"code",access_type:"offline",prompt:"consent",scope:scope.join(" "),state}).toString()}`}
if(provider==="slack"){const clientId=process.env.SLACK_CLIENT_ID;if(!clientId)throw new Error("SLACK_CLIENT_ID_NOT_CONFIGURED");authorizationUrl=`https://slack.com/oauth/v2/authorize?${new URLSearchParams({client_id:clientId,scope:"chat:write,channels:read,groups:read",redirect_uri:redirectUri,state}).toString()}`}
if(provider==="hubspot"){const clientId=process.env.HUBSPOT_CLIENT_ID;if(!clientId)throw new Error("HUBSPOT_CLIENT_ID_NOT_CONFIGURED");authorizationUrl=`https://app.hubspot.com/oauth/authorize?${new URLSearchParams({client_id:clientId,redirect_uri:redirectUri,scope:"oauth crm.objects.contacts.read crm.objects.contacts.write",state}).toString()}`}
if(provider==="square"){const clientId=process.env.SQUARE_APPLICATION_ID;if(!clientId)throw new Error("SQUARE_APPLICATION_ID_NOT_CONFIGURED");authorizationUrl=`https://connect.squareup.com/oauth2/authorize?${new URLSearchParams({client_id:clientId,scope:"MERCHANT_PROFILE_READ ITEMS_READ ITEMS_WRITE ORDERS_READ ORDERS_WRITE",session:"false",state,redirect_uri:redirectUri}).toString()}`}
return res.json({authorizationUrl,redirectUri})}catch(e){return fail(res,e)}}
