import type {VercelRequest,VercelResponse} from "@vercel/node";import {admin} from "../../server/http";import {encryptCredentials,verifyState} from "../../server/credentials";
async function json(url:string,init:RequestInit){const r=await fetch(url,init),b=await r.json().catch(()=>({}));if(!r.ok||b.error)throw new Error(b.error_description||b.error?.message||b.error||`OAUTH_${r.status}`);return b}
function page(res:VercelResponse,ok:boolean,message:string){return res.status(ok?200:400).setHeader("Content-Type","text/html; charset=utf-8").send(`<!doctype html><html><body style="font-family:system-ui;background:#fafbf9;color:#1e2420;padding:40px"><div style="max-width:520px;margin:auto;background:white;border:1px solid #e5eae5;border-radius:20px;padding:28px"><h1>${ok?"Connected to Tauranto":"Connection failed"}</h1><p>${message.replace(/[<>&]/g,"")}</p><p>You can return to the Tauranto app and tap Refresh.</p></div></body></html>`)}
export default async function handler(req:VercelRequest,res:VercelResponse){try{if(req.query.error)return page(res,false,String(req.query.error_description||req.query.error));const code=String(req.query.code||""),state=verifyState<any>(String(req.query.state||""));if(!code)throw new Error("AUTHORIZATION_CODE_MISSING");const redirectUri=(process.env.PUBLIC_API_URL?.replace(/\/$/,"")||`https://${req.headers.host}`)+"/api/integrations/oauth-callback";let token:any,config:any={};
if(state.provider==="gmail"||state.provider==="google_calendar")token=await json("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({code,client_id:process.env.GOOGLE_CLIENT_ID||"",client_secret:process.env.GOOGLE_CLIENT_SECRET||"",redirect_uri:redirectUri,grant_type:"authorization_code"})});
if(state.provider==="slack"){token=await json("https://slack.com/api/oauth.v2.access",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({code,client_id:process.env.SLACK_CLIENT_ID||"",client_secret:process.env.SLACK_CLIENT_SECRET||"",redirect_uri:redirectUri})});config={team_id:token.team?.id,team_name:token.team?.name}}
if(state.provider==="hubspot")token=await json("https://api.hubapi.com/oauth/v1/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"authorization_code",client_id:process.env.HUBSPOT_CLIENT_ID||"",client_secret:process.env.HUBSPOT_CLIENT_SECRET||"",redirect_uri:redirectUri,code})});
if(state.provider==="square"){token=await json("https://connect.squareup.com/oauth2/token",{method:"POST",headers:{"Content-Type":"application/json","Square-Version":"2026-07-15"},body:JSON.stringify({client_id:process.env.SQUARE_APPLICATION_ID||"",client_secret:process.env.SQUARE_APPLICATION_SECRET||"",code,grant_type:"authorization_code",redirect_uri:redirectUri})});config={merchant_id:token.merchant_id}}
if(!token)throw new Error("UNSUPPORTED_PROVIDER");const db=admin(),display={gmail:"Gmail",google_calendar:"Google Calendar",slack:"Slack",hubspot:"HubSpot",square:"Square"}[state.provider as string]||state.provider;const encrypted=encryptCredentials(token);const {data:existing}=await db.from("integrations").select("id").eq("restaurant_id",state.restaurantId).eq("provider",state.provider).maybeSingle();const row={restaurant_id:state.restaurantId,provider:state.provider,display_name:display,status:"connected",encrypted_credentials:encrypted,config:{...config,connected_at:new Date().toISOString()}};const {error}=existing?await db.from("integrations").update(row).eq("id",existing.id):await db.from("integrations").insert(row);if(error)throw error;await db.from("audit_events").insert({restaurant_id:state.restaurantId,actor_id:state.userId,event:"integration_connected",metadata:{provider:state.provider}});return page(res,true,`${display} is now connected securely.`)}catch(e){return page(res,false,e instanceof Error?e.message:"OAuth connection failed")}}
