import React,{useEffect,useRef}from'react';
import{Pressable,ScrollView,StyleSheet,Text,View}from'react-native';
import{darkColors}from'../theme/tokens';import{useTheme}from'../theme/ThemeContext';

export function PageCarousel<T extends string>({items,active,onChange}:{items:readonly T[];active:T;onChange:(item:T)=>void}){
 const{dark}=useTheme(),ref=useRef<ScrollView>(null),layouts=useRef<Record<string,{x:number;width:number}>>({});
 useEffect(()=>{const l=layouts.current[active];if(l)ref.current?.scrollTo({x:Math.max(0,l.x-18),animated:true})},[active]);
 return <View style={[s.shell,dark&&s.shellDark]}><ScrollView ref={ref} horizontal showsHorizontalScrollIndicator={false} bounces decelerationRate="fast" snapToAlignment="start" contentContainerStyle={s.content}>{items.map(item=>{const selected=item===active;return <Pressable key={item} onLayout={e=>layouts.current[item]=e.nativeEvent.layout} onPress={()=>onChange(item)} style={[s.item,dark&&s.itemDark,selected&&s.selected,dark&&selected&&s.selectedDark]} accessibilityRole="tab" accessibilityState={{selected}}><Text numberOfLines={1} style={[s.text,dark&&s.textDark,selected&&s.activeText,dark&&selected&&s.activeTextDark]}>{String(item)}</Text></Pressable>})}</ScrollView></View>
}
const s=StyleSheet.create({shell:{marginBottom:20,borderWidth:1,borderColor:'#E3E5E3',borderRadius:22,backgroundColor:'#FFF',paddingVertical:7,shadowColor:'#14251D',shadowOpacity:.06,shadowRadius:12,shadowOffset:{width:0,height:5}},shellDark:{backgroundColor:darkColors.card,borderColor:darkColors.border},content:{paddingHorizontal:8,gap:8},item:{minWidth:104,height:44,paddingHorizontal:20,borderRadius:18,borderWidth:1,borderColor:'#E1E4E1',backgroundColor:'#FFF',alignItems:'center',justifyContent:'center'},itemDark:{backgroundColor:darkColors.card,borderColor:darkColors.border},selected:{backgroundColor:'#EEE8FF',borderColor:'#D5C7FF'},selectedDark:{backgroundColor:'#3A3158',borderColor:'#6D5AA8'},text:{fontFamily:'NunitoSans_800ExtraBold',fontSize:12,color:'#59605C'},textDark:{color:darkColors.textMuted},activeText:{fontFamily:'NunitoSans_900Black',color:'#6049A8'},activeTextDark:{color:'#D9CFFF'}});