import React,{useEffect,useMemo,useRef,useState}from"react";
import{Animated,Easing,StyleSheet,Text,View}from"react-native";
import{Video,ResizeMode}from"expo-av";

const SCENES=[
 {uri:"https://videos.pexels.com/video-files/8626675/8626675-uhd_3840_2160_25fps.mp4",eyebrow:"HANDS-FREE KITCHEN",title:"Keep service moving while you speak",body:"Give Tauranto instructions naturally while your team keeps cooking and serving."},
 {uri:"https://videos.pexels.com/video-files/3371015/3371015-hd_1920_1080_30fps.mp4",eyebrow:"LIVE RESTAURANT OPERATIONS",title:"Coordinate the team without stopping",body:"Voice-led workflows help the kitchen, counter and service team stay aligned during the rush."},
 {uri:"https://videos.pexels.com/video-files/5657164/5657164-uhd_4096_2160_30fps.mp4",eyebrow:"TABLE & GUEST SERVICE",title:"Turn spoken requests into action",body:"Keep attention on guests while Tauranto helps move restaurant tasks forward behind the scenes."},
 {uri:"https://videos.pexels.com/video-files/6683745/6683745-uhd_3840_2160_25fps.mp4",eyebrow:"INVENTORY & CONTROL",title:"Manage more without living on a screen",body:"Track operational work, supplies and follow-ups while staying present on the restaurant floor."}
];

export function RestaurantVideoHero(){
 const[index,setIndex]=useState(0);const fades=useMemo(()=>SCENES.map((_,i)=>new Animated.Value(i===0?1:0)),[]);const text=useRef(new Animated.Value(1)).current;
 useEffect(()=>{const timer=setInterval(()=>{setIndex(current=>{const next=(current+1)%SCENES.length;text.setValue(0);Animated.parallel(fades.map((fade,i)=>Animated.timing(fade,{toValue:i===next?1:0,duration:1100,easing:Easing.bezier(.22,.61,.36,1),useNativeDriver:true}))).start();Animated.timing(text,{toValue:1,duration:760,delay:220,easing:Easing.out(Easing.cubic),useNativeDriver:true}).start();return next})},7500);return()=>clearInterval(timer)},[fades,text]);
 return <View style={s.wrap}>{SCENES.map((scene,i)=><Animated.View key={scene.uri} pointerEvents="none" style={[StyleSheet.absoluteFill,{opacity:fades[i]}]}><Video source={{uri:scene.uri}} style={StyleSheet.absoluteFill} resizeMode={ResizeMode.COVER} isMuted shouldPlay={i===index||i===(index+1)%SCENES.length} isLooping useNativeControls={false}/></Animated.View>)}<View style={s.scrim}/><View style={s.voiceBadge}><View style={s.voiceDot}/><Text style={s.voiceBadgeText}>TAURANTO LISTENING</Text></View><Animated.View style={[s.copy,{opacity:text,transform:[{translateY:text.interpolate({inputRange:[0,1],outputRange:[10,0]})}]}]}><Text style={s.eyebrow}>{SCENES[index].eyebrow}</Text><Text style={s.title}>{SCENES[index].title}</Text><Text style={s.body}>{SCENES[index].body}</Text></Animated.View><View style={s.dots}>{SCENES.map((_,i)=><View key={i} style={[s.dot,i===index&&s.dotActive]}/>)}</View></View>
}
const s=StyleSheet.create({wrap:{height:214,borderRadius:20,overflow:"hidden",backgroundColor:"#173C2B",marginBottom:13},scrim:{...StyleSheet.absoluteFillObject,backgroundColor:"rgba(5,20,13,.34)"},voiceBadge:{position:"absolute",top:14,left:16,flexDirection:"row",alignItems:"center",gap:6,backgroundColor:"rgba(6,27,18,.70)",borderWidth:1,borderColor:"rgba(255,255,255,.22)",borderRadius:16,paddingHorizontal:10,paddingVertical:6},voiceDot:{width:7,height:7,borderRadius:4,backgroundColor:"#61E39B"},voiceBadgeText:{fontFamily:"NunitoSans_900Black",fontSize:9.5,letterSpacing:.8,color:"#F4FFF8"},copy:{position:"absolute",left:18,right:42,bottom:18},eyebrow:{fontFamily:"NunitoSans_900Black",fontSize:10.5,letterSpacing:1.2,color:"#D9F5E4",marginBottom:4},title:{fontFamily:"NunitoSans_900Black",fontSize:24,lineHeight:28,color:"#fff"},body:{fontFamily:"NunitoSans_700Bold",fontSize:13,lineHeight:17,color:"rgba(255,255,255,.92)",marginTop:5},dots:{position:"absolute",right:13,bottom:18,gap:5},dot:{width:5,height:5,borderRadius:3,backgroundColor:"rgba(255,255,255,.45)"},dotActive:{height:17,backgroundColor:"#fff"}});