import React,{useEffect}from"react";
import{View,Text,Pressable,StyleSheet,Platform}from"react-native";
import{useSafeAreaInsets}from"react-native-safe-area-context";
import{Ionicons}from"@expo/vector-icons";
import{TabName}from"../../App";
import{colors}from"../theme/tokens";
import{useTheme}from"../theme/ThemeContext";
const nav:any[]=[{id:"home",name:"Today",label:"Home",icon:"home-outline",active:"home",tint:"#F1F6F3",ink:"#4F7968"},{id:"tables",name:"Tables",label:"Tables",icon:"restaurant-outline",active:"restaurant",tint:"#F4F1F7",ink:"#75698A"},{id:"inventory",name:"Inventory",label:"Inventory",icon:"cube-outline",active:"cube",tint:"#F0F5F7",ink:"#5E7F8D"},{id:"insights",name:"Analytics",label:"Insights",icon:"stats-chart-outline",active:"stats-chart",tint:"#F8F4ED",ink:"#8B7255"},{id:"activity",name:"Activity",label:"Activity",icon:"pulse-outline",active:"pulse",tint:"#F8F1F2",ink:"#8B6670"}];
export function Shell({children,tab,onTabChange,pending}:{children:React.ReactNode;tab:TabName;onTabChange:(t:TabName)=>void;pending:number;onVoice:()=>void}){const insets=useSafeAreaInsets(),{dark}=useTheme();useEffect(()=>{if(Platform.OS!=="web"||typeof document==="undefined")return;document.body.style.margin="0";document.body.style.overflow="hidden"},[]);return <View style={[s.shell,dark&&s.shellDark]}><View style={s.content}>{children}</View>{tab!=="Today"&&<Pressable accessibilityLabel="Open configuration menu" onPress={()=>onTabChange("More")} style={[s.menuButton,dark&&s.menuButtonDark,{top:Math.max(insets.top,8)+2}]}><Ionicons name="menu" size={21} color={dark?"#fff":"#152019"}/></Pressable>}<View pointerEvents="box-none" style={[s.navStage,{bottom:Math.max(insets.bottom,8)+7}]}><View style={[s.bottom,dark&&s.bottomDark]}>{nav.map(x=><Nav key={x.id} x={x} tab={tab} pending={pending} change={onTabChange} dark={dark}/>)}</View></View></View>}
function Nav({x,tab,pending,change,dark}:any){const selected=tab===x.name;return <Pressable accessibilityLabel={x.label} onPress={()=>change(x.name)} style={({pressed})=>[s.navItem,pressed&&{opacity:.55}]}><View style={[s.iconBox,{backgroundColor:dark?'rgba(255,255,255,.06)':x.tint}]}><Ionicons name={selected?x.active:x.icon} size={21} color={x.ink}/>{x.id==="activity"&&pending>0&&<View style={s.badge}><Text style={s.badgeText}>{pending>9?"9+":pending}</Text></View>}</View><Text style={[s.navLabel,dark&&s.navLabelDark,selected&&s.navLabelActive,{color:selected?x.ink:dark?'#A2ADA7':'#727974'}]}>{x.label}</Text>{selected&&<View style={[s.activeLine,{backgroundColor:x.ink}]}/>}</Pressable>}
const s=StyleSheet.create({shell:{flex:1,backgroundColor:colors.cream,overflow:"hidden"},shellDark:{backgroundColor:"#101512"},content:{flex:1,overflow:"hidden"},menuButton:{position:"absolute",left:12,zIndex:80,width:38,height:38,borderRadius:12,backgroundColor:"rgba(255,255,255,.94)",borderWidth:1,borderColor:"#E1E7E3",alignItems:"center",justifyContent:"center",shadowColor:"#000",shadowOpacity:.07,shadowRadius:8,elevation:4},menuButtonDark:{backgroundColor:"rgba(34,42,37,.94)",borderColor:"#39443E"},navStage:{position:"absolute",left:18,right:18,zIndex:60,alignItems:"center"},bottom:{width:"100%",maxWidth:530,height:68,borderRadius:34,flexDirection:"row",alignItems:"center",justifyContent:"space-around",paddingHorizontal:8,backgroundColor:"rgba(255,255,255,.91)",borderWidth:1,borderColor:"rgba(218,222,219,.78)",shadowColor:"#102018",shadowOpacity:.07,shadowRadius:14,shadowOffset:{width:0,height:5},elevation:12},bottomDark:{backgroundColor:"rgba(25,32,28,.90)",borderColor:"rgba(65,78,70,.85)"},navItem:{flex:1,height:62,alignItems:"center",justifyContent:"center",position:"relative"},iconBox:{width:35,height:31,borderRadius:11,alignItems:"center",justifyContent:"center"},navLabel:{fontFamily:"NunitoSans_700Bold",fontSize:9.5,lineHeight:13,color:"#727974",marginTop:1},navLabelDark:{color:"#A2ADA7"},navLabelActive:{fontFamily:"NunitoSans_800ExtraBold"},activeLine:{position:"absolute",bottom:1,width:27,height:2.5,borderRadius:2,opacity:.82},badge:{position:"absolute",right:-3,top:-4,minWidth:17,height:17,paddingHorizontal:4,borderRadius:9,backgroundColor:"#4D8B70",alignItems:"center",justifyContent:"center",borderWidth:2,borderColor:"#fff"},badgeText:{fontFamily:"NunitoSans_800ExtraBold",fontSize:7.5,color:"#fff"}});