import React,{useEffect,useRef,useState} from "react";
import {Alert,Platform,Pressable,StyleSheet,Switch,Text,TextInput,View} from "react-native";
import * as Speech from "expo-speech";import {Ionicons} from "@expo/vector-icons";import {ExpoSpeechRecognitionModule,useSpeechRecognitionEvent} from "expo-speech-recognition";import {colors,radius,shadow} from "../theme/tokens";import {VoiceCommand} from "../lib/models";
type Mode="off"|"standby"|"recording"|"working";
export type VoiceStatus={mode:Mode;message:string;lastHeard:string};
const wakeAliases=["hey tauranto","hi tauranto","hello tauranto","okay tauranto","ok tauranto","hey toronto","hi toronto","hello toronto"];
const normalize=(v:string)=>v.toLowerCase().replace(/[^a-z0-9\s]/g," ").replace(/\s+/g," ").trim();
const wakeMatch=(v:string)=>wakeAliases.find(a=>normalize(v).includes(a));
const commandAfterWake=(v:string)=>{const n=normalize(v),alias=wakeAliases.find(a=>n.includes(a));if(!alias)return"";return n.slice(n.indexOf(alias)+alias.length).replace(/^(please|can you|could you|would you)\s+/i,"").trim()};
const draft=(transcript:string):VoiceCommand=>({id:`capture-${Date.now()}`,transcript,title:"Restaurant instruction",summary:transcript,type:"task",status:"pending",createdAt:new Date().toISOString(),targets:[],confidence:1});
export function VoiceComposer({onCommand,enabled,onEnabledChange,onStatusChange,visible=true}:{onCommand:(command:VoiceCommand)=>void|Promise<void>;enabled:boolean;onEnabledChange:(enabled:boolean)=>void;onStatusChange?:(status:VoiceStatus)=>void;visible?:boolean}){const[mode,setMode]=useState<Mode>("off"),[message,setMessage]=useState(""),[transcript,setTranscript]=useState(""),[manual,setManual]=useState(false),[lastHeard,setLastHeard]=useState("");const modeRef=useRef<Mode>("off"),enabledRef=useRef(false),finishRef=useRef<ReturnType<typeof setTimeout>|null>(null),commandRef=useRef(""),submittingRef=useRef(false),wakeTriggeredRef=useRef(false),recognitionRunningRef=useRef(false);const changeMode=(m:Mode)=>{modeRef.current=m;setMode(m)};const clearFinish=()=>{if(finishRef.current)clearTimeout(finishRef.current);finishRef.current=null};
useSpeechRecognitionEvent("start",()=>{recognitionRunningRef.current=true});
useSpeechRecognitionEvent("result",event=>{const heard=event.results[0]?.transcript?.trim()||"";if(!heard)return;setLastHeard(heard);if(modeRef.current==="standby"){const wake=wakeMatch(heard);if(!wake||wakeTriggeredRef.current)return;wakeTriggeredRef.current=true;const trailing=commandAfterWake(heard);commandRef.current=trailing;setTranscript(trailing);changeMode("recording");setMessage("I’m listening…");if(trailing)scheduleFinish(event.isFinal?1400:2200);return}if(modeRef.current==="recording"){let text=heard;const wake=wakeMatch(text);if(wake)text=commandAfterWake(text);if(text){commandRef.current=text;setTranscript(text)}scheduleFinish(event.isFinal?1400:2200)}});
useSpeechRecognitionEvent("end",()=>{recognitionRunningRef.current=false;if(!enabledRef.current||submittingRef.current)return;if(modeRef.current==="recording"&&commandRef.current.trim().length>2)void finishCommand(false);else if(modeRef.current!=="working")changeMode("standby")});
useSpeechRecognitionEvent("error",event=>{recognitionRunningRef.current=false;if(["aborted","no-speech"].includes(event.error))return;setMessage(`Voice service: ${event.message||event.error}. Tap Speak now to retry.`);if(modeRef.current!=="working")changeMode("standby")});
useEffect(()=>{if(enabled!==enabledRef.current)void toggleStandby(enabled)},[enabled]);useEffect(()=>{onStatusChange?.({mode,message,lastHeard})},[mode,message,lastHeard,onStatusChange]);useEffect(()=>()=>{enabledRef.current=false;clearFinish();ExpoSpeechRecognitionModule.abort();Speech.stop()},[]);
async function permission(){const p=await ExpoSpeechRecognitionModule.requestPermissionsAsync();if(!p.granted){Alert.alert("Microphone permission needed","Allow microphone and speech recognition access in device Settings.");return false}return true}
async function startRecognition(target:Mode="standby"){if(!enabledRef.current||submittingRef.current||recognitionRunningRef.current)return;if(!(await permission()))return;clearFinish();wakeTriggeredRef.current=target==="recording";changeMode(target);setMessage(target==="recording"?"I’m listening…":Platform.OS==="web"?"Keep Tauranto open for standby.":"Listening for “Hey Tauranto”…");try{ExpoSpeechRecognitionModule.start({lang:"en-US",interimResults:true,continuous:true,requiresOnDeviceRecognition:false,addsPunctuation:true})}catch(e){setMessage(e instanceof Error?e.message:"Could not start voice listening.")}}
function scheduleFinish(delay=1800){clearFinish();finishRef.current=setTimeout(()=>void finishCommand(true),delay)}
async function finishCommand(stopRecognition=true){if(submittingRef.current)return;const text=commandRef.current.trim();clearFinish();if(text.length<3){commandRef.current="";setTranscript("");wakeTriggeredRef.current=false;changeMode("standby");return}if(stopRecognition&&recognitionRunningRef.current){recognitionRunningRef.current=false;ExpoSpeechRecognitionModule.stop()}await submit(text)}
async function toggleStandby(on:boolean){enabledRef.current=on;clearFinish();Speech.stop();commandRef.current="";setTranscript("");setLastHeard("");wakeTriggeredRef.current=false;if(!on){recognitionRunningRef.current=false;ExpoSpeechRecognitionModule.abort();changeMode("off");setMessage("");return}if(!(await permission())){enabledRef.current=false;onEnabledChange(false);changeMode("off");return}await startRecognition("standby")}
async function submit(value=transcript){const text=value.trim();if(!text||submittingRef.current)return;submittingRef.current=true;changeMode("working");setMessage("Understanding and validating your instruction…");try{await onCommand(draft(text));setTranscript("");commandRef.current="";setMessage("Instruction received. Check the command status for approval or execution.");Speech.stop();Speech.speak("Got it.",{rate:.96,pitch:1});}catch(e){setMessage(e instanceof Error?e.message:"Could not process that instruction.");Speech.stop();Speech.speak("I couldn't process that instruction. Please check the app.",{rate:.96,pitch:1})}finally{submittingRef.current=false;wakeTriggeredRef.current=false;if(enabledRef.current){changeMode("standby");setMessage("Ready. Tap Speak now for another command.")}else changeMode("off")}}
async function speakNow(){if(mode==="recording"){await finishCommand();return}if(recognitionRunningRef.current){recognitionRunningRef.current=false;ExpoSpeechRecognitionModule.abort()}commandRef.current="";setTranscript("");wakeTriggeredRef.current=true;setTimeout(()=>void startRecognition("recording"),180)}
const recording=mode==="recording",working=mode==="working";if(!visible)return null;return <View><View style={s.card}><View style={s.top}><View style={[s.dot,mode==="standby"&&s.ready,recording&&s.live]}/><View style={{flex:1}}><Text style={s.status}>{mode==="standby"?"Tauranto is ready":recording?"Listening to your command":working?"Tauranto is working":"Tauranto is off"}</Text><Text style={s.statusCopy}>{mode==="standby"?"Say “Hey Tauranto” while standby is active, or tap Speak now":recording?"Speak naturally — Tauranto submits after you stop":working?"Understanding and validating your instruction":"Turn Tauranto on from here or Home"}</Text></View><Switch value={enabled} onValueChange={onEnabledChange} trackColor={{false:colors.line,true:"#E5C95A"}} thumbColor="white"/></View><Text style={s.prompt}>{recording?"I’m listening.":working?"One moment…":"What needs to happen?"}</Text><Text style={s.help}>Try: “Hey Tauranto, email the flour vendor and ask for 20 bags tomorrow.”</Text>{!!transcript&&<View style={s.transcript}><Text style={s.label}>HEARD</Text><Text style={s.transcriptText}>“{transcript}”</Text></View>}{!!message&&<View style={s.message}><Ionicons name="information-circle-outline" size={20} color={colors.leafDeep}/><Text style={s.messageText}>{message}</Text></View>}<Pressable disabled={working} onPress={()=>void speakNow()} style={[s.speak,recording&&s.stop,working&&{opacity:.6}]}><View style={s.speakIcon}><Ionicons name={recording?"stop":"mic"} size={28} color="white"/></View><View style={{flex:1}}><Text style={s.speakTitle}>{recording?"Finish now":"Speak now"}</Text><Text style={s.speakCopy}>{recording?"Or stop speaking and Tauranto will submit":"Tap for immediate listening"}</Text></View></Pressable><Pressable onPress={()=>setManual(v=>!v)} style={s.type}><Ionicons name="keypad-outline" size={23} color={colors.ink}/><Text style={s.typeText}>{manual?"Close typing":"Type instead"}</Text></Pressable></View>{manual&&<View style={s.inputBar}><TextInput value={transcript} onChangeText={v=>{setTranscript(v);commandRef.current=v}} multiline placeholder="Type a restaurant instruction" style={s.input}/><Pressable onPress={()=>void submit()} style={s.send}><Ionicons name="arrow-up" size={22} color="white"/></Pressable></View>}</View>}
const s=StyleSheet.create({card:{backgroundColor:"#E8F0DB",borderRadius:26,padding:20,borderWidth:1,borderColor:"#D3DFC4",...shadow},top:{flexDirection:"row",alignItems:"center",gap:12},dot:{width:13,height:13,borderRadius:7,backgroundColor:colors.muted},ready:{backgroundColor:"#E5C95A"},live:{backgroundColor:colors.tomato},status:{fontFamily:"DMSans_700Bold",fontSize:18,color:colors.ink},statusCopy:{fontFamily:"DMSans_400Regular",fontSize:14,lineHeight:19,color:colors.inkSoft,marginTop:3},prompt:{fontFamily:"DMSans_700Bold",fontSize:30,lineHeight:37,color:colors.ink,marginTop:24},help:{fontFamily:"DMSans_400Regular",fontSize:14,lineHeight:21,color:colors.inkSoft,marginTop:8},transcript:{backgroundColor:"#FFFFFFD9",borderRadius:radius.md,padding:15,marginTop:15},label:{fontFamily:"DMSans_700Bold",fontSize:11,letterSpacing:1,color:colors.leafDeep},transcriptText:{fontFamily:"DMSans_600SemiBold",fontSize:17,lineHeight:24,color:colors.ink,marginTop:7},message:{flexDirection:"row",gap:8,backgroundColor:"#FFFFFF8F",borderRadius:13,padding:12,marginTop:13},messageText:{flex:1,fontFamily:"DMSans_500Medium",fontSize:13,lineHeight:18,color:colors.inkSoft},speak:{minHeight:72,borderRadius:18,backgroundColor:colors.leafDeep,flexDirection:"row",alignItems:"center",gap:12,paddingHorizontal:15,marginTop:17},stop:{backgroundColor:colors.tomato},speakIcon:{width:46,height:46,borderRadius:14,backgroundColor:"#FFFFFF22",alignItems:"center",justifyContent:"center"},speakTitle:{fontFamily:"DMSans_700Bold",fontSize:17,color:"white"},speakCopy:{fontFamily:"DMSans_400Regular",fontSize:13,color:"#FFFFFFD0",marginTop:3},type:{height:56,borderRadius:16,backgroundColor:colors.paper,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:9,borderWidth:1,borderColor:"#D4DDCA",marginTop:10},typeText:{fontFamily:"DMSans_700Bold",fontSize:15,color:colors.ink},inputBar:{flexDirection:"row",alignItems:"flex-end",backgroundColor:colors.paper,borderRadius:radius.md,borderWidth:1,borderColor:colors.line,marginTop:10,padding:9,gap:8},input:{flex:1,minHeight:50,maxHeight:110,fontFamily:"DMSans_400Regular",fontSize:16,color:colors.ink,padding:10},send:{width:50,height:50,borderRadius:15,backgroundColor:colors.leafDeep,alignItems:"center",justifyContent:"center"}});