create extension if not exists pgcrypto;

do $$ begin create type public.member_role as enum ('owner','admin','manager','operator','viewer'); exception when duplicate_object then null; end $$;
do $$ begin create type public.command_status as enum ('needs_clarification','pending_approval','approved','rejected','queued','executing','completed','failed','cancelled'); exception when duplicate_object then null; end $$;
do $$ begin create type public.approval_status as enum ('pending','approved','rejected'); exception when duplicate_object then null; end $$;

create table if not exists public.profiles (id uuid primary key references auth.users on delete cascade, full_name text not null default '', email text, phone text, created_at timestamptz not null default now());
create table if not exists public.restaurants (id uuid primary key default gen_random_uuid(), name text not null, timezone text not null default 'America/New_York', approval_mode text not null default 'unanimous' check (approval_mode in ('unanimous','any_one')), created_at timestamptz not null default now());
create table if not exists public.restaurant_members (restaurant_id uuid references public.restaurants on delete cascade, user_id uuid references public.profiles on delete cascade, role public.member_role not null default 'operator', can_approve boolean not null default false, active boolean not null default true, primary key(restaurant_id,user_id));
create table if not exists public.commands (id uuid primary key default gen_random_uuid(), restaurant_id uuid not null references public.restaurants on delete cascade, created_by uuid references public.profiles, source text not null check(source in('voice','typed')), transcript text not null, action_type text not null, title text not null, summary text not null, parameters jsonb not null default '{}', risk text not null check(risk in('low','medium','high','critical')), confidence numeric not null check(confidence between 0 and 1), ambiguities jsonb not null default '[]', confirmation_question text, status public.command_status not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.approvals (id uuid primary key default gen_random_uuid(), command_id uuid not null references public.commands on delete cascade, approver_id uuid not null references public.profiles, status public.approval_status not null default 'pending', note text, decided_at timestamptz, created_at timestamptz not null default now(), unique(command_id,approver_id));
create table if not exists public.execution_jobs (id uuid primary key default gen_random_uuid(), command_id uuid not null unique references public.commands on delete cascade, status text not null default 'queued', attempts int not null default 0, idempotency_key text not null unique, last_error text, created_at timestamptz not null default now(), completed_at timestamptz);
create table if not exists public.integrations (id uuid primary key default gen_random_uuid(), restaurant_id uuid not null references public.restaurants on delete cascade, provider text not null, display_name text not null, encrypted_credentials text, status text not null default 'disconnected', config jsonb not null default '{}', created_at timestamptz not null default now());
create table if not exists public.audit_events (id bigint generated always as identity primary key, restaurant_id uuid not null references public.restaurants on delete cascade, command_id uuid references public.commands on delete set null, actor_id uuid references public.profiles, event text not null, metadata jsonb not null default '{}', created_at timestamptz not null default now());

alter table public.profiles enable row level security; alter table public.restaurants enable row level security; alter table public.restaurant_members enable row level security; alter table public.commands enable row level security; alter table public.approvals enable row level security; alter table public.integrations enable row level security; alter table public.audit_events enable row level security; alter table public.execution_jobs enable row level security;
create or replace function public.is_member(rid uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from restaurant_members where restaurant_id=rid and user_id=auth.uid() and active)$$;

drop policy if exists "own profile" on public.profiles; create policy "own profile" on public.profiles for select using(id=auth.uid());
drop policy if exists "member restaurants" on public.restaurants; create policy "member restaurants" on public.restaurants for select using(public.is_member(id));
drop policy if exists "members see team" on public.restaurant_members; create policy "members see team" on public.restaurant_members for select using(public.is_member(restaurant_id));
drop policy if exists "members see commands" on public.commands; create policy "members see commands" on public.commands for select using(public.is_member(restaurant_id));
drop policy if exists "approvers see assignments" on public.approvals; create policy "approvers see assignments" on public.approvals for select using(approver_id=auth.uid() or exists(select 1 from commands c where c.id=command_id and public.is_member(c.restaurant_id)));
drop policy if exists "members see integrations" on public.integrations; create policy "members see integrations" on public.integrations for select using(public.is_member(restaurant_id));
drop policy if exists "members see audit" on public.audit_events; create policy "members see audit" on public.audit_events for select using(public.is_member(restaurant_id));

create index if not exists commands_restaurant_created on public.commands(restaurant_id,created_at desc); create index if not exists approvals_approver_status on public.approvals(approver_id,status); create index if not exists audit_restaurant_created on public.audit_events(restaurant_id,created_at desc);
